### PR TITLE
Fix initial filament loading

### LINKED ISSUE #11158: Filament Pressure Advance values are not created at the gcode
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.2 dev

### Operating System (OS)

Windows

### OS Version

Windows 11

### Additional system information

_No response_

### Printer

Sovol SV08

### How to reproduce

Choose a Filament with pressure advance activated.
Slice a test cube
Export the gcode
open the gcode with an editor and search for the "filament gcode section" The PA values are not in there.

No Problem with Version 2.3.1

### Actual results

PA Vaules are not integrated in the gcode file.

### Expected results

PA Vaules should be integrated in the gcode file.

### Project file & Debug log uploads

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=Würfel_id_0_copy_0 CENTER=175,175 POLYGON=[[157.5,157.5],[192.5,157.5],[192.5,192.5],[157.5,192.5],[157.5,157.5]]
M73 P0 R20
;TYPE:Custom
START_PRINT EXTRUDER=230 BED=60 Chamber=0 PRINT_MIN=152.59,152.59 PRINT_MAX=197.41,197.41 MATERIAL=PLA
G90
G21
M83 ; use relative distances for extrusion
; Filament gcode
M106 S0
;LAYER_CHANGE
;Z:0.25
;HEIGHT:0.25
TIMELAPSE_TAKE_FRAME
G92 E0
G1 E-.8 F3900
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=3000 ACCEL_TO_DECEL=1500
G1 X154.14 Y154.245 F36000

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

V2.3.1 hast not his bug

### LINKED ISSUE #11218: Filament  changing no longer works
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.2 Dev 05533a7

### Operating System (OS)

Windows

### OS Version

Windows 11 25H2

### Additional system information

_No response_

### Printer

Sovol SV06 Plus Klipper

### How to reproduce

Either split object into parts and change color on one part, or add color change in the timeline, doesn't matter

### Actual results

Image 

Zero filament changes show, all the mass is for some reason for one filament but not the other. Printer doesn't pause for a filament change as it should and did on earlier versions.

### Expected results

Proper readout saying 1 filament change, and the weight divided between the two filaments.

### Project file & Debug log uploads

[22-45_acp.zip](https://github.com/user-attachments/files/23269246/22-45_acp.zip) project

[debug_Fri_Oct_31_16_59_18_20780.log.zip](https://github.com/user-attachments/files/23269264/debug_Fri_Oct_31_16_59_18_20780.log.zip) logs

### Checklist of files to include

- [x] Log file
- [x] Project file

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Noisyfox**
Fix #11218
Fix #11158

### CODE REVIEW

**Comment by Noisyfox** [comment]
@ianalexis @yw4z Could you give this a try and see if it works

**Comment by ianalexis** [comment]
Both worked for me
imagen
imagen

**Comment by yw4z** [comment]
thanks for sending fix
works as expected. but it adds a small retraction. also 2.3.1 doesnt have retraction. both test same cube and same filament preset https://github.com/SoftFever/OrcaSlicer/pull/11329#issuecomment-3518003363
Screenshot-20251113193118
retraction doesnt exist on K1 config

**Comment by valerii-bokhan** [comment]
But it does not fix issues for BBL printers either. I am testing on BBL A1 mini.

If worked for me only if I remove the entire block of code presented in this PR.

File: src/libslic3r/GCode.cpp [hunk 1]
```diff
@@ -2810,16 +2810,18 @@ void GCode::_do_export(Print& print, GCodeOutputStream &file, ThumbnailsGenerato
...
+        // add the missing filament start gcode in machine start gcode
+        {
+            DynamicConfig config;
+            config.set_key_value("filament_extruder_id", new ConfigOptionInt((int)(initial_non_support_extruder_id)));
+            config.set_key_value("layer_num", new ConfigOptionInt(m_layer_index));
+            std::string filament_start_gcode = this->placeholder_parser_process("filament_start_gcode", print.config().filament_start_gcode.values.at(initial_non_support_extruder_id), initial_non_support_extruder_id,&config);
+            file.writeln(filament_start_gcode);
+            // mark the first filament used in print
+            file.write_format(";VT%d\n", initial_extruder_id);
+        }
```
Comment (valerii-bokhan) [inline src/libslic3r/GCode.cpp:2824]: During my tests on BBL A1 mini, I can say that this changes does not fix PA.

Should we add this code in the end of the block to fix it?
```
        if (this->config().enable_pressure_advance.get_at(initial_non_support_extruder_id)) {
            file.write(this->m_writer.set_pressure_advance(this->config().pressure_advance.get_at(initial_non_support_extruder_id)));
        }

Comment (Noisyfox) [reply src/libslic3r/GCode.cpp:2824]: Yes the problem is that the initial filament loading process for bbl printers are now part of the print start code, so it only works for k value set on the printer/ams side, not our own pa values. I’ll see if I could find a solution.

Comment (Noisyfox) [reply src/libslic3r/GCode.cpp:2824]: End up using the solution you proposed. Could you give it a try?

**Comment by Noisyfox** [comment]
> works as expected. but it adds a small retraction

It was a change BBS introduced here
https://github.com/bambulab/BambuStudio/commit/fff787345625a0031934e609b1b3709e39decd4a#diff-cb3d09d2073b6e9032c65d07aa8f10d166324a53136b2aa1288f7b76f7d94319R6067

I'll see if we could skip the retraction if no z-hop is performed.


UPD: I think I'll do a proper fix in a separate PR.

File: src/libslic3r/GCode.cpp (hunk 1 above)
Comment (valerii-bokhan) [reply src/libslic3r/GCode.cpp:2824]: PA works with this change - I could see the `M900` command.

**Comment by valerii-bokhan** [comment]
A question about `M600` command - should it work for BBL printers?

I am asking because I print with single color only and not sure how I can test if it's working correctly.

At least, I didn't find any place in the code where the `M600` command is being added.

**Comment by Noisyfox** [comment]
> A question about `M600` command - should it work for BBL printers?
> 
> I am asking because I print with single color only and not sure how I can test if it's working correctly.
> 
> At least, I didn't find any place in the code where the `M600` command is being added.

BBL printer profiles define their own `change_filament_gcode` that doesn't use M600.
