### PR TITLE
Fix hangs when trying to edit printer on Linux (#11714)

### LINKED ISSUE #11714: crashing when trying to edit printer
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

https://github.com/OrcaSlicer/OrcaSlicer/commit/7fa6175b4fbb230d26d3fa1d77cbe3964e7de1fb

# System Details Report:

## Hardware Information:
- **Hardware Model:**                              ASUS ROG STRIX X670E-E GAMING WIFI
- **Memory:**                                      32.0 GiB
- **Processor:**                                   AMD Ryzen™ 9 7950X3D × 32
- **Graphics:**                                    AMD Radeon™ RX 7900 XTX

## Software Information:
- **OS Name:**                                     Manjaro Linux
- **OS Type:**                                     64-bit
- **GNOME Version:**                               49
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.19.0-rc4-1-MANJARO

### Additional information

Neither **`Flatpak`** nor **`AppImage`** do work.

### How to reproduce + Actual results

https://github.com/user-attachments/assets/40bb6f98-6c29-4eaa-ad4d-e418e321fea8

### Expected results

not crashing 😊

### Anything else?

I know that this is working on Windows.

### Attachments

- [x] log file

[debug_Mon_Jan_05_16_23_54_2.log.0.txt](https://github.com/user-attachments/files/24436030/debug_Mon_Jan_05_16_23_54_2.log.0.txt)

### PR DESCRIPTION
**Pull request by crpalmer**
On linux, some users report that attempting to edit the printer caused OrcaSlicer to hang.
Fixes #11714

### CODE REVIEW

**Comment by discip** [comment]
@crpalmer
## Thank you!

File: src/slic3r/GUI/Plater.cpp [hunk 1]
```diff
@@ -1714,10 +1714,13 @@ Sidebar::Sidebar(Plater *parent)
             p->editing_filament = -1;
             if (p->combo_printer->switch_to_tab())
                 p->editing_filament = 0;
-            // ORCA clicking edit button not triggers wxEVT_KILL_FOCUS wxEVT_LEAVE_WINDOW make changes manually to prevent stucked colors when opening printer settings
-            p->panel_printer_preset->SetBorderColor(panel_color.bd_normal);
-            p->btn_edit_printer->Hide();
-            p->panel_printer_preset->Layout();
+
```
Comment (yw4z) [inline src/slic3r/GUI/Plater.cpp]: can you add a description to here 
"// FIX crash on wxGTK, directly modifying UI (self->Hide() / parent->Layout()) inside a button event can crash because callbacks are not re-entrant, leaving widgets in an inconsistent state"

**Comment by yw4z** [comment]
@igiannakas can you test this on macOS? here is what to test https://github.com/OrcaSlicer/OrcaSlicer/issues/11714#issuecomment-3715885361
border colors has to be switch to normal state / colors after opening edit dialog
no issue on windows, not sure same behaviour exist on all linux distros

you can merge if no specific issues with macOS

**Comment by discip** [comment]
@SoftFever
@Noisyfox
@igiannakas
@ianalexis
Could someone please merge this?
Having to edit the corresponding **`.json`** file to change settings is really tiring. 😩

File: src/slic3r/GUI/Plater.cpp (hunk 1 above)
Comment (ianalexis) [inline src/slic3r/GUI/Plater.cpp]:
```suggestion
// ORCA: FIX crash on wxGTK, directly modifying UI (self->Hide() / parent->Layout()) inside a button event can crash because callbacks are not re-entrant, leaving widgets in an inconsistent state
```

File: src/slic3r/GUI/Plater.cpp [hunk 2]
```diff
@@ -1714,10 +1714,13 @@ Sidebar::Sidebar(Plater *parent)
             p->editing_filament = -1;
             if (p->combo_printer->switch_to_tab())
                 p->editing_filament = 0;
-            // ORCA clicking edit button not triggers wxEVT_KILL_FOCUS wxEVT_LEAVE_WINDOW make changes manually to prevent stucked colors when opening printer settings
-            p->panel_printer_preset->SetBorderColor(panel_color.bd_normal);
-            p->btn_edit_printer->Hide();
-            p->panel_printer_preset->Layout();
+// ORCA: FIX crash on wxGTK, directly modifying UI (self->Hide() / parent->Layout()) inside a button event can crash because callbacks are not re-entrant, leaving widgets in an inconsistent state
```
Comment (ianalexis) [inline src/slic3r/GUI/Plater.cpp]:
```suggestion
            // ORCA: FIX crash on wxGTK, directly modifying UI (self->Hide() / parent->Layout()) inside a button event can crash because callbacks are not re-entrant, leaving widgets in an inconsistent state
```

**Comment by ianalexis** [comment]
Tested in x11 both Appimage and Flatpak, lgtm.
Only waiting for a Mac test just in case.
