### PR TITLE
Fix bed mesh algorithm for 3 point bicubic algorightm

### LINKED ISSUE #4875: Adaptive bed mesh generates unusable probe count on large machines
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

windows 10

### Additional system information

_No response_

### Printer

Custom 500mm based on ratrig profile - running klipper

### How to reproduce

I sliced an object that is 267mm by 72mm. 
mesh min to 25,45  
mesh max to 480,480
probe point distance 40,40
mesh margin 5

### Actual results

the output from this: 

BED_MESH_CALIBRATE mesh_min=104.192,204.609 mesh_max=390.808,296.61 ALGORITHM=lagrange PROBE_COUNT=8,3 ADAPTIVE=1 ADAPTIVE_MARGIN=0

to which klipper gives error :  
!! bed_mesh: cannot exceed a probe_count of 6 when using lagrange interpolation. Configured Probe Count: 7, 3

if forcing bicubic there is also a probe count error for a difference reason

### Expected results

I would expect it wouldnt be difficult to force a certain probe count to make klipper happy

### Project file & Debug log uploads

[Cube_0.16mm_PETG_2h11m.zip](https://github.com/SoftFever/OrcaSlicer/files/14878211/Cube_0.16mm_PETG_2h11m.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by igiannakas**
# Description
Fixes #4875, #4694 

Checks the below conditions for Klipper firmware:
1. If the total number of mesh points is 6 -> use Lagrange interpolation
2. If the total number of mesh points is greater than 6, use Bicubic
3. If bicubic is used, ensure that at least 4 points are present in both X and Y. 

This appears consistent with the Klipper documentation below and the KAMP implementation.

algorithm: lagrange
Default Value: lagrange
The algorithm used to interpolate the mesh. May be lagrange or bicubic. **Lagrange interpolation is capped at 6 probed points** as oscillation tends to occur with a larger number of samples. **Bicubic interpolation requires a minimum of 4 probed points along each axis**, if less than 4 points are specified then lagrange sampling is forced. If mesh_pps is set to 0 then this value is ignored as no mesh interpolation is done.

### CODE REVIEW

File: src/libslic3r/GCode.cpp [hunk 1]
```diff
@@ -2352,11 +2352,17 @@ void GCode::_do_export(Print& print, GCodeOutputStream &file, ThumbnailsGenerato
         auto probe_dist_y  = std::max(1., m_config.bed_mesh_probe_distance.value.y());
         int  probe_count_x = std::max(3, (int) std::ceil(mesh_bbox.size().x() / probe_dist_x));
         int  probe_count_y = std::max(3, (int) std::ceil(mesh_bbox.size().y() / probe_dist_y));
-        this->placeholder_parser().set("bed_mesh_probe_count", new ConfigOptionInts({probe_count_x, probe_count_y}));
         auto bed_mesh_algo = "bicubic";
-        if (probe_count_x < 4 || probe_count_y < 4) {
+        int min_points = 4; // bicubic needs 4 probe points per axis
+        if (probe_count_x + probe_count_y <= 6) { // lagrange needs up to a total of 6 mesh points
```
Comment (SoftFever) [inline src/libslic3r/GCode.cpp:2357]: should it be `probe_count_x * probe_count_y <= 6` instead?

Comment (igiannakas) [reply src/libslic3r/GCode.cpp:2357]: Oh yes! I’ll correct it

Comment (igiannakas) [reply src/libslic3r/GCode.cpp:2357]: Thing is it will never trigger this algo though if I am reading the code right? As the min probe points is 3 * 3 in the lines above?

**Comment by igiannakas** [comment]
So I've been checking out how KAMP does it

```
    {% if (([points_x, points_y]|max) > 6) %}                                                                                       # 
        {% set algorithm = "bicubic" %}                                                                                             # 
        {% set min_points = 4 %}                                                                                                    # 
    {% else %}                                                                                                                      # Calculate if algorithm should be bicubic or lagrange
        {% set algorithm = "lagrange" %}                                                                                            # 
        {% set min_points = 3 %}                                                                                                    # 
    {% endif %}  
```

So they take the max of points X and points Y and if either is >6 -> use Bicubic. So for Orca should this snippet be?
```
        auto bed_mesh_algo = "bicubic";
        int min_points = 4; // bicubic needs 4 probe points per axis
        if (std::max(probe_count_x, probe_count_y) <= 6) { // lagrange needs up to a total of 6 mesh points
            bed_mesh_algo = "lagrange";
            min_points = 3;
        }
```

File: src/libslic3r/GCode.cpp (hunk 1 above)
Comment (SoftFever) [reply src/libslic3r/GCode.cpp]: The max probe count will be 2x3 or 3x2 for Lagrange.
For a typical probe distance say 50mm, it will be 100x150(or 150x100), pretty common actually.

**Comment by SoftFever** [comment]
why do we need the min point?

**Comment by SoftFever** [comment]
> So I've been checking out how KAMP does it
> 
> ```
>     {% if (([points_x, points_y]|max) > 6) %}                                                                                       # 
>         {% set algorithm = "bicubic" %}                                                                                             # 
>         {% set min_points = 4 %}                                                                                                    # 
>     {% else %}                                                                                                                      # Calculate if algorithm should be bicubic or lagrange
>         {% set algorithm = "lagrange" %}                                                                                            # 
>         {% set min_points = 3 %}                                                                                                    # 
>     {% endif %}  
> ```
> 
> So they take the max of points X and points Y and if either is >6 -> use Bicubic. So for Orca should this snippet be?
> 
> ```
>         auto bed_mesh_algo = "bicubic";
>         int min_points = 4; // bicubic needs 4 probe points per axis
>         if (std::max(probe_count_x, probe_count_y) <= 6) { // lagrange needs up to a total of 6 mesh points
>             bed_mesh_algo = "lagrange";
>             min_points = 3;
>         }
> ```

According to Klipper doc, this is wrong too

**Comment by igiannakas** [comment]
OK I think it's done (?). Git has been a bit slow and difficult this evening for some reason

**Review by SoftFever — APPROVED** [review]
LGTM
