### PR TITLE
Fix object's list text color on Linux (GH-2086)

### LINKED ISSUE #2086: Linux -- Process - Objects - Text black.
### OrcaSlicer Version

1.6.6 and 1.7.0 beta

### OS version

6.1.51-1-MANJARO (64-bit)

### Additional system information

Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.1.51-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3770K CPU @ 3.50GHz
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1080/PCIe/SSE2

### Printer

Custom profile. #Customized Robo3dR1+

### How to reproduce

1. Make sure the system is in dark mode
2. have `"dark_color_mode": "1",` in the OrcaSlicer.conf  (shouldn't matter)
3. Select printer profile
4. Select filaments
5. Have Advanced enabled (shouldn't matter)
6. Select Objects button

### Actual results

image

image

### Expected results

Readable text.

### Project file & Debug log uploads

[OrcaCube.zip](https://github.com/SoftFever/OrcaSlicer/files/12582858/OrcaCube.zip)

[debug_Mon_Sep_11_23_55_52_27964.log.0.log](https://github.com/SoftFever/OrcaSlicer/files/12582864/debug_Mon_Sep_11_23_55_52_27964.log.0.log)

### Checklist of files to include

- [X] Log file
- [X] Project file

### PR DESCRIPTION
**Pull request by mdziekon**
Partial solution for #2086 (do not close - this PR does not fully fix the issue, it just makes one place better)

This PR focuses on fixing the Object's list text rendering on linux-based OSes. As some people reported, for Linux users with Dark mode enabled, the Object's list renders its text in black-ish color, making it impossible to read. I'm not sure about that in general, but for me at least, switching temporarily to light mode also didn't fix the problem (comparing to other places where that trick does fix the problem, temporarily), as it was rendered all white.

The proposed fix for that is quite simple - for linux platforms, apply the base text color, which then seems to be handled by dark mode color changing as expected.

#### Before

obraz
obraz

#### After

obraz
obraz

### CODE REVIEW

**Comment by discip** [comment]
@mdziekon
> fixes #2086


If you don't want the related issue to be closed, you would need to change the quoted line as exactly that will definitely happen due to [GitHub Docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) if you leave it like this. 😊

Maybe something like:

_partially fixes issue #2086_

**Comment by mdziekon** [comment]
> @mdziekon
> 
> > fixes #2086
> 
> If you don't want the related issue to be closed, you would need to change the quoted line as exactly that will definitely happen due to [GitHub Docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) if you leave it like this. 😊
> 
> Maybe something like:
> 
> _partially fixes issue #2086_

Good advice, changed to:
> Partially solution for #2086

File: src/slic3r/GUI/GUI_ObjectList.cpp [hunk 1]
```diff
@@ -91,6 +91,13 @@ ObjectList::ObjectList(wxWindow* parent) :
     wxDataViewCtrl(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxDV_MULTIPLE)
 {
     wxGetApp().UpdateDVCDarkUI(this, true);
+
+#ifdef __linux__
```
Comment (SoftFever) [inline src/slic3r/GUI/GUI_ObjectList.cpp:95]: LGTM

**Review by SoftFever — APPROVED** [review]
