### PR TITLE
Fix Filltrapezoidal layer rotation with infill combination

### LINKED ISSUE #13275: Grid infill with Fill Multiline does not change direction
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.2

### Operating System (OS)

Windows

### OS Version

11

### Additional system information

_No response_

### Printer

Prusa XL 5T

### How to reproduce

1. New project
2. Add primitive (I used a simple cube)
3. In "Strength" tab I set
    1. Fill Multiline to 2
    2. Sparse Infill Pattern to Grid

### Actual results

Every layer has the Grid infill pattern with the same "direction".
Other patterns such as Honeycomb and Triangles rotate the infill direction each layer maximizing the strength.

Here you can see the seam is all in the same direction for each layer
Image

While here you can see that the seam direction is rotated for each layer
Image

### Expected results

Grid infill should rotate 90 degrees for each layer.

### Project file & Debug log uploads

[orca_grid_multiline_rotation_issue.zip](https://github.com/user-attachments/files/26859962/orca_grid_multiline_rotation_issue.zip)

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by RF47**
# Description

In this pull request, I correct the rotation logic for the Filltrapezoidal infill (grid and  triangles multiline infill ) when using an infill combination.
Previously, rotation was based on the layer ID, which meant that when using infill combination, the layers did not rotate correctly

image

Fix #13275

# Test
[orca_grid_multiline_rotation_issue.zip](https://github.com/user-attachments/files/26861469/orca_grid_multiline_rotation_issue.zip)

### CODE REVIEW

File: src/libslic3r/Fill/FillRectilinear.cpp [hunk 1]
```diff
@@ -3082,6 +3082,7 @@ bool FillRectilinear::fill_surface_trapezoidal(
 
     // Use extended object bounding box for consistent pattern across layers
     BoundingBox bb = this->extended_object_bounding_box();
+    const size_t infill_layer_id = (surface->thickness_layers > 0) ? this->layer_id / surface->thickness_layers : this->layer_id;
```
Comment (ianalexis) [inline src/libslic3r/Fill/FillRectilinear.cpp:3085]: Hacelo acá directamente un entero y así no guardas la variable en size_t y necesite volvé ra convertirlo después.

File: src/libslic3r/Fill/FillRectilinear.cpp [hunk 2]
```diff
@@ -3174,7 +3175,7 @@ bool FillRectilinear::fill_surface_trapezoidal(
 
         //  Align bounding box to the grid
         bb.merge(align_to_grid(bb.center(), Point(period,h)));
-        const int    layer_mod = layer_id % 3;
+        const int    layer_mod = int(infill_layer_id % 3);
```
Comment (RF47) [inline src/libslic3r/Fill/FillRectilinear.cpp]:
```suggestion
        const size_t    layer_mod = infill_layer_id % 3;
```

File: src/libslic3r/Fill/FillRectilinear.cpp (hunk 1 above)
Comment (RF47) [reply src/libslic3r/Fill/FillRectilinear.cpp:3085]: dejo  todo en size_t y listo

**Review by ianalexis — APPROVED** [review]
LGTM
