### PR TITLE
Fix #3311: filament Load / Unload time was not used in time estimation

### LINKED ISSUE #3311: Filament Load / Unload time didn't change ETA
### OrcaSlicer Version

1.8.1 and 1.9.0

### OS version

Windows 11

### Additional system information

_No response_

### Printer

Voron 2.4

### How to reproduce

Slice
change load / unload time
Slice
Same time

### Actual results

Didn't change ETA

### Expected results

Recalculate ETA

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/13778594/log.zip)
[oddish.zip](https://github.com/SoftFever/OrcaSlicer/files/13778596/oddish.zip)

### Checklist of files to include

- [X] Log file
- [x] Project file

### PR DESCRIPTION
**Pull request by eoyilmaz**
The `config.filament_load_time.values` and `config.filament_unload_time.values` are completely ignored. This was working in PrusaSlicer and apparently BBS converted the `GCodeProcessor::TimeProcessor.filament_load_times` and `GCodeProcessor::TimeProcessor.filament_unload_times` from being `std::vector<float>` to just `float` and they were using the BBS specific and currently hidden `machine_load_filament_time` and `machine_unload_filament_time` config values. Reverted that change by copying those lines from PrusaSlicer.

### CODE REVIEW

**Comment by SoftFever** [comment]
> The `config.filament_load_time.values` and `config.filament_unload_time.values` are completely ignored. This was working in PrusaSlicer and apparently BBS converted the `GCodeProcessor::TimeProcessor.filament_load_times` and `GCodeProcessor::TimeProcessor.filament_unload_times` from being `std::vector<float>` to just `float` and they were using the BBS specific and currently hidden `machine_load_filament_time` and `machine_unload_filament_time` config values. Reverted that change by copying those lines from PrusaSlicer.

Thank for digging into the issue.
Yeah, I previously hid `machine_load_filament_time`/`machine_unload_filament_time` for non-BBL printers. I was debating whether it makes sense to have load/unload times per filament/tool. However, since I don't have extensive experience with multi-material printing, I decided to retain PrusaSlicer's settings when porting SEMM.

Meanwhile, the proposed change will break compatibility with BBL machines. Can you add special handling codes for BBL machines? Something like

```
if(s_IsBBLPrinter) {
 m_time_processor.filament_load_times.resize(1);
 m_time_processor.filament_load_times[0] = static_cast<float>(machine_load_filament_time->values);
}
```
You can use `s_IsBBLPrinter` to decide if it's BBL machine.

**Review by SoftFever — CHANGES_REQUESTED** [review]
Please ref to my comments

**Comment by eoyilmaz** [comment]
Hey @SoftFever yeah sure, let me look in to that.

**Comment by eoyilmaz** [comment]
Hey @SoftFever I update the code to keep the BBS printer compatibility, I tested it with both a BBL and non-BBL printer and it is working as expected in both of these conditions 👍

File: src/libslic3r/GCode/GCodeProcessor.cpp [hunk 1]
```diff
@@ -4357,14 +4394,23 @@ void GCodeProcessor::set_travel_acceleration(PrintEstimatedStatistics::ETimeMode
...
+                   ((extruder_id < m_time_processor.filament_load_times.size()) ? m_time_processor.filament_load_times[extruder_id] :
+                                                                                  m_time_processor.filament_load_times.front());
+    }
 }
 
 float GCodeProcessor::get_filament_unload_time(size_t extruder_id)
 {
-    //BBS: change unload time to machine config and all extruder has same value
-    return m_time_processor.extruder_unloaded ? 0.0f : m_time_processor.filament_unload_times;
+    return (m_time_processor.filament_unload_times.empty() || m_time_processor.extruder_unloaded) ?
```
Comment (SoftFever) [inline src/libslic3r/GCode/GCodeProcessor.cpp:4410]: This code also works.
Just so that we keep the logic consistent, can we either:
1. Add `if (s_IsBBLPrinter)` logic in this function
2. Or Remove `if (s_IsBBLPrinter)` logic in get_filament_load_time() function?

Comment (eoyilmaz) [reply src/libslic3r/GCode/GCodeProcessor.cpp:4410]: aah sorry that one slipped from my eyes 👍

**Comment by eoyilmaz** [comment]
Okay updated `GCodeProcessor::get_filament_unload_time()` too 👍

**Review by SoftFever — APPROVED** [review]
Looks good

**Comment by SoftFever** [comment]
Thank you for you work 👍 
Merged.
