### PR TITLE
Fix AMS filament selection compatible check

### LINKED ISSUE #9112: Error when selecting custom filament in Bambu AMS list
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.0 Build 70931e5

### Operating System (OS)

Windows

### OS Version

Windows 11

### Additional system information

_No response_

### Printer

Bambu Lab P1S

### How to reproduce

1. Go to Device Tab
2. Edit an AMS filament
3. Select custom filament (Polymaker CoPE), and choose any color.
4. Press Confirm. The error will appear.

"You need to select the material type and color first."

### Actual results

Image

### Expected results

Window disappears and new filament is applied, and shown in the AMS list in the device tab.

### Project file & Debug log uploads

Project file: It happens with any project, but here is my current project just in case: [puzzlebox-4m-3N-3H-12b-12c-60h-1B6-0G4-1w2-2t-3z-1M-10X-0p7-0g4-8s-2r-1R666667-e-Z-1T-0y1-0Z2-1.zip](https://github.com/user-attachments/files/19496649/puzzlebox-4m-3N-3H-12b-12c-60h-1B6-0G4-1w2-2t-3z-1M-10X-0p7-0g4-8s-2r-1R666667-e-Z-1T-0y1-0Z2-1.zip)
Log file: [log.zip](https://github.com/user-attachments/files/19496645/log.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

I did not see the Polymaker CoPE option while using 2.2.0, so I'm assuming the custom filament showing in the AMS drop down list is new in 2.3.0 as an option, but other "user presets" I have made in the past aren't showing up in the "custom filaments" list. I don't remember doing anything different with the Polymaker CoPE user preset that I didn't do with the others. I will attach a couple screenshots. 

Image
Image

### PR DESCRIPTION
**Pull request by Noisyfox**
Fix #9112

### CODE REVIEW

File: src/slic3r/GUI/AMSMaterialsSetting.cpp [hunk 1]
```diff
@@ -992,10 +992,11 @@ void AMSMaterialsSetting::on_select_filament(wxCommandEvent &evt)
                 auto filament_item = map_filament_items[m_comboBox_filament->GetValue().ToStdString()];
                 std::string filament_id   = filament_item.filament_id;
                 if (it->filament_id.compare(filament_id) == 0) {
+                    ConfigOption *       printer_opt  = it->config.option("compatible_printers");
+                    ConfigOptionStrings *printer_strs = dynamic_cast<ConfigOptionStrings *>(printer_opt);
                     bool has_compatible_printer = false;
-                    std::string preset_name            = it->name;
-                    for (std::string printer_name : printer_names) {
-                        if (preset_name.find(printer_name) != std::string::npos) {
+                    for (auto printer_str : printer_strs->values) {
```
Comment (SoftFever) [inline src/slic3r/GUI/AMSMaterialsSetting.cpp:998]: Should we take care of the case where the compatible printers are empty, which is the case if the filament is from the Orca Filament Library?

Comment (SoftFever) [reply src/slic3r/GUI/AMSMaterialsSetting.cpp:998]: It might actually be tricky to handle that case. I think it's fine for now. We don't need to do it. At the moment, all global profiles have overridden version for BBL anyway.

**Review by SoftFever — APPROVED** [review]
LGTM
