### PR TITLE
Fix: GCodeViewer displaying inconsistent data in title and body

### LINKED ISSUE #11910: 2.3.2 Nightly: UI displays filament flow on non-extruding moves
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.2-dev

### Operating System (OS)

macOS

### OS Version

macOS 26.1

### Additional system information

_No response_

### Printer

Anycubic Kobra S1

### How to reproduce

1. Slice anything on any printer
2. Switch to "Flow"
3. Read the message below while the print head is moving without extruding

### Actual results

Slicer calculate flow based on speed: 23.64 mm^3\s which even more than max flow rate in filament settings.

Image

### Expected results

Because no filament is extruded during travel movements and Orca correctly identifies them as travel, the flow parameter is unnecessary and can be omitted or set to 0.0 mm³/s.

### Project file & Debug log uploads

I uploaded the 3MF archive for formality, but based on my observations it is not actually needed. This issue occurs with any configuration and with any slicing.

[UI_issue.3mf.zip](https://github.com/user-attachments/files/24545964/UI_issue.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Sabriel-Koh**
# Description
Previously, the GCodeViewer would display stats in for flow, width, height, and line type in the title/summarized view even while there was no extrusion (e.g., travelling). It has been fixed to only show N/A, matching the display in the detailed view.

Additionally, actual flow is no longer displayed in the title. It only shows the actual flow for the end of a segment, and so may give the wrong impression that the actual flow is consistently low. It is also more consistent with its absence in the detailed view.

Fixes #11910 

# Screenshots/Recordings/Graphs

Line/Feature Type Bef/Aft
imageimage

Line Height Bef/Aft
imageimage

Line Width Bef/Aft
imageimage

Flow Bef/Aft
imageimage

Actual Flow Removed
image

## Tests
Checked the GCodeViewer on the same project file on pre- and post- fix builds

### CODE REVIEW

File: src/slic3r/GUI/GCodeViewer.cpp [hunk 1]
```diff
@@ -320,15 +320,24 @@ void GCodeViewer::SequentialView::Marker::render_position_window(const libvgcode
         sprintf(buf, "X: %.3f, Y: %.3f, Z: %.3f Speed: %.0f ", vertex.position[0], vertex.position[1], vertex.position[2], vertex.feedrate);
         switch (view_type) {
             case libvgcode::EViewType::Height: {
-                sprintf(buf, "%s %s%.2f", buf, _u8L("Height: ").c_str(), vertex.height);
+                if (vertex.is_extrusion())
+                    sprintf(buf, "%s %s%.2f", buf, _u8L("Height: ").c_str(), vertex.height);
```
Comment (SoftFever) [inline src/slic3r/GUI/GCodeViewer.cpp]: can we make folowing changes?

```cpp

const auto NA_TXT = _u8L("N/A").c__str();

....

  
const auto is_extrution = vertex.is_extrusion();  
sprintf(buf, "%s %s%.2f", buf, _u8L("Height: ").c_str(), is_extrusion ? vertex.height : NA_TXT);

```

Comment (SoftFever) [reply src/slic3r/GUI/GCodeViewer.cpp]: same for other parts

Comment (Sabriel-Koh) [reply src/slic3r/GUI/GCodeViewer.cpp]: Updated to be more concise and using const vars to reduce repetition
