### PR TITLE
Fix issue that support surfaces get filtered out unexpectly 

### LINKED ISSUE #7935: Supports (multimaterial): Changing Top Z distance inhibits bottom interface material change
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0

### Operating System (OS)

Windows

### OS Version

Win10

### Additional system information

_No response_

### Printer

Bambu Labs X1C

### How to reproduce

Looking to run different materials for support interface - in this case PLA for a PETG print.
Everything worked as expected until test prints suggested that the PETG layer on top of the PLA support interface was a little over squished. I thought it would be an easy fix by just setting a small "Top X Distance" which had the side effect of breaking the bottom support interface.

Please compare the two images
image

image

Bug appears to be linked to the support style - Snug is affected while default or grid are not.

### Actual results

Alternative material support interface only placed on top of the support.

### Expected results

Alternative material support interface on both top and bottom of the support.

### Project file & Debug log uploads

[Octavia 2025 Shortarse Bracket v3.1 X570DU [Serenade@0.4 ORCA 3MF] fault.zip](https://github.com/user-attachments/files/18312963/Octavia.2025.Shortarse.Bracket.v3.1.X570DU.Serenade%400.4.ORCA.3MF.fault.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Noisyfox**
Fix #7935

image

### CODE REVIEW

File: src/libslic3r/Support/SupportMaterial.cpp [hunk 1]
```diff
@@ -603,94 +603,10 @@ void PrintObjectSupportMaterial::generate(PrintObject &object)
...
-            object.add_support_layer(layer_id ++, this_layer_id_interface, height_min, zavg);
-            if (num_interfaces && ! this_layer_contacts_only)
-                ++ layer_id_interface;
-        }
-        i = j;
-    }
+#ifdef SLIC3R_DEBUG
+    SupportGeneratorLayersPtr layers_sorted =
+#endif // SLIC3R_DEBUG
+    generate_support_layers(object, raft_layers, bottom_contacts, top_contacts, intermediate_layers, interface_layers, base_interface_layers);
```
Comment (Noisyfox) [inline src/libslic3r/Support/SupportMaterial.cpp:609]: This is the core part that fixes the problem. Everything else is changes needed to make the code compile. No logic changes at all EXCEPT this one.
