### PR TITLE
Avoid unnecessary travel in scarf seam

### LINKED ISSUE #9139: Arachne Causing Constant Z-Hops With Scarf Seam
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.0 Build 70931e5

### Operating System (OS)

Windows

### OS Version

Windows 11

### Additional system information

CPU: Ryzen 9 5900x
GPU: RTX 3090
Memory: 64GB DDR4

### Printer

Bambu Lab A1 Mini 

### How to reproduce

Enable Arachne + Scarf Seams  on attached file

### Actual results

Printer will repeatedly slow speed and Z-hop when printing the scarf section, causing blobbing and much slower printing time.

### Expected results

Issue does not occur when Classic wall generation is selected. Scarf sections print at specified speed without stopping and starting and z-hopping constantly.

### Project file & Debug log uploads

[debug_Sat_Mar_29_09_52_12_27904.log.zip](https://github.com/user-attachments/files/19522846/debug_Sat_Mar_29_09_52_12_27904.log.zip)

[Oneup_EDC_Dynaplug_Outer_Cap_w_Taper_-_110mm.zip](https://github.com/user-attachments/files/19522847/Oneup_EDC_Dynaplug_Outer_Cap_w_Taper_-_110mm.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

### Anything else?

See images and videos here:
https://photos.app.goo.gl/SZHb3BeCzKQqBs1T7

### PR DESCRIPTION
**Pull request by Noisyfox**
Fix #9139

Old:
old

New:
new

### CODE REVIEW

File: src/libslic3r/GCode.cpp [hunk 1]
```diff
@@ -5140,10 +5140,15 @@ std::string GCode::_extrude(const ExtrusionPath &path, std::string description,
         return lerp(m_nominal_z - height, m_nominal_z, z_ratio);
     };
 
+    bool slop_need_z_travel = false;
```
Comment (henrivdr) [inline src/libslic3r/GCode.cpp:5143]: This looks like a typo.

Comment (Noisyfox) [reply src/libslic3r/GCode.cpp]: Nice catch!
