### PR TITLE
Fix UTF-8 corruption in Custom G-code editor (°C and other Unicode characters)

### LINKED ISSUE #11502: GCODE Corruption with Symbols
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.2-dev

### Operating System (OS)

Windows

### OS Version

Win10

### Additional system information

_No response_

### Printer

N/A

### How to reproduce

1. Edit some GCODE in the GCODE editor (the actual _editor_, so click the _edit_ button above any GCODE section, the editor that shows all the placeholders and actually uses a fixed-width font)
2. Put some symbols in there - I was trying the degree symbol - `°` (followed by C, of course)
3. Save
4. Re-open editor
5. Observe corruption
6. Save - without changing anything
7. Re-open editor again
8. Observe even more corruption and random chars appearing
9. Rinse/repeat, it will keep adding chars.

### Actual results

Image

Was wondering why my logs had weird symbols, so looked, went and fixed the gcode, hit save, re-opened it and this:

Image

### Expected results

The content should not be changed when saving.

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kisslorand**
This PR fixes an issue where certain characters (for example the degree symbol ° used in °C) became corrupted after opening and saving the Custom G-code editor multiple times.

#### What was the problem?

When users added symbols like ° inside Start/End G-code, the editor would show them correctly the first time, but after reopening the dialog a few times the text would slowly change into strange characters.

#### How to reproduce

- Open any Custom G-code field
- Add a line containing °C
- Save the dialog
- Reopen it several times
- The text begins to change into unreadable characters

#### What this PR changes

The Custom G-code editor now properly loads and saves text that contains symbols such as °, so these characters stay exactly as the user typed them. This keeps Custom G-code stable across editing sessions and prevents slow corruption of Unicode characters.

#### Result

- °C and similar symbols remain correct
- No more “weird characters” appearing after multiple reopen/save cycles
- Custom G-code is preserved accurately

Fixes #11502

### CODE REVIEW

File: src/slic3r/GUI/EditGCodeDialog.cpp [hunk 1]
```diff
@@ -131,7 +132,8 @@ EditGCodeDialog::~EditGCodeDialog()
 
 std::string EditGCodeDialog::get_edited_gcode() const
 {
-    return into_u8(m_gcode_editor->GetValue());
+    wxString text = m_gcode_editor->GetValue();
+    return std::string(text.ToUTF8());
```
Comment (Noisyfox) [inline src/slic3r/GUI/EditGCodeDialog.cpp:136]: I think `into_u8` does the exact same thing?

Comment (kisslorand) [reply src/slic3r/GUI/EditGCodeDialog.cpp:136]: Yeah, they output the same thing.
I just used `ToUTF8()` here to keep it consistent with the `FromUTF8()` on the load side.
