### PR TITLE
[Bug fix] Fixes "Wipe before external loop" causing blobs on single wall perimeters

### LINKED ISSUE #3450: "Wipe before external loop" causing blobs on single wall perimeters
### OrcaSlicer Version

1.9.0-beta

### OS version

MacOS Sonoma 14.2

### Additional system information

_No response_

### Printer

P1P

### How to reproduce

I have couple of objects with only 2 perimeters transitioning into a single perimeter in the last couple of layers.
While the "Wipe before external loop" is almost completely removing the visible seam on the 2 perimeter walls, it is creating a blob on the single perimeter wall.
- Material: PETG

## Suspicion
The Wipe while retracting may not be working as expected or there is issue with the pa.

## "Wipe before external loop" on

IMG_6914
IMG_6915

## "Wipe before external loop" off
IMG_6916

### Expected results

It should not over extrude and create such blob on single perimeter walls.

### Project file & Debug log uploads

[Cube.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13824247/Cube.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### LINKED ISSUE #3603: Retractions in vase mode when Travel distance threshold set to 0
### OrcaSlicer Version

1.9.0

### OS version

OS: Windows 10

### Additional system information

_No response_

### Printer

Snapmaker J1S

### How to reproduce

1. Add a primitive cylinder
2. Enable spiralize vase
3. Set Travel distance threshold to 0 in either machine settings or filament settings
4. Slice

### Actual results

image

### Expected results

image
There are no travel moves in vase mode (at least after the initial layers) so there shouldn't be any retractions. 

### Project file & Debug log uploads

[Cylinder.zip](https://github.com/SoftFever/OrcaSlicer/files/13895937/Cylinder.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### PR DESCRIPTION
**Pull request by igiannakas**
Fixes #3450 

Introduced a check to ensure that a neighbouring internal perimeter exists at the deretraction point when wipe before external loop is enabled. This avoids a situation where the de-retraction is done partly in mid-air, causing an external surface zit. 

**Before:**
image

**After:**
image

Regular use case is unaffected.

image

### CODE REVIEW

File: src/libslic3r/GCode.hpp [hunk 1]
```diff
@@ -347,8 +347,12 @@ class GCode {
     std::string     preamble();
     // BBS
     std::string     change_layer(coordf_t print_z);
-    std::string     extrude_entity(const ExtrusionEntity &entity, std::string description = "", double speed = -1.);
-    std::string     extrude_loop(ExtrusionLoop loop, std::string description, double speed = -1.);
+    // Orca: pass the complete collection of region perimeters to the extrude loop to check whether the wipe before external loop
+    // should be executed
+    std::string     extrude_entity(const ExtrusionEntity &entity, std::string description = "", double speed = -1., ExtrusionEntitiesPtr region_perimeters = ExtrusionEntitiesPtr());
```
Comment (SoftFever) [inline src/libslic3r/GCode.hpp:352]: It would be better to pass ExtrusionEntitiesPtr by const reference instead to avoid creatign a copy of the vector

File: src/libslic3r/GCode.hpp [hunk 2]
```diff
@@ -347,8 +347,12 @@ class GCode {
...
+    // Orca: pass the complete collection of region perimeters to the extrude loop to check whether the wipe before external loop
+    // should be executed
+    std::string     extrude_loop(ExtrusionLoop loop, std::string description, double speed = -1., ExtrusionEntitiesPtr region_perimeters = ExtrusionEntitiesPtr());
```
Comment (SoftFever) [inline src/libslic3r/GCode.hpp:355]: Same here

**Review by SoftFever — CHANGES_REQUESTED** [review]

File: src/libslic3r/GCode.hpp (hunk 1 above)
Comment (igiannakas) [reply src/libslic3r/GCode.hpp]: Done

File: src/libslic3r/GCode.hpp (hunk 2 above)
Comment (igiannakas) [reply src/libslic3r/GCode.hpp]: Done

**Review by SoftFever — APPROVED** [review]
Look good!

**Comment by SoftFever** [comment]
Thanks!
