### PR TITLE
Fan mover: Ignore non-part cooling fans (SoftFever/OrcaSlicer#7171)

### LINKED ISSUE #7171: Fan speed incorrect for first layer after filament change
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0

### Operating System (OS)

macOS

### OS Version

15.0.1

### Additional system information

N/A , slicing issue, not crash/render issue.

### Printer

Bambu X1C

### How to reproduce

1.  Slice attached project.
2. Inspect Layer 200, notice normal fan speed of 18%.
3. Inspect layer 201 , with abnormal fan speed of 100%, which should be ~18-19%.

### Actual results

Notice that layer 201 improperly has 100% fan speed, as inherited from the filament start GCODE sequence, but the normal "on layer change set fan speed" logic doesn't not appear to trigger, leaving the fan @ 100% for the whole layer, until the following layer.    This results in very weak layer bonding in this PETG print (but problem also would apply to most non-PLA/TPU prints).
Screenshot 2024-10-20 at 11 23 23 AM

This is bad because it can result in prints looking like this, with an "easy break" layer inserted in by mistake, where the print will likely be extremely weak:
Screenshot 2024-10-20 at 11 43 12 AM

And here's the offending filament start GCODE that doesn't get clobbered (like it should) by a layer-change fan instruction:

Screenshot 2024-10-20 at 11 23 09 AM

### Expected results

Fan speed should be normally set according to the filament cooling rules, not according to filament start code during a filament change.  The proper result here would be a fan speed of ~18-19% based on subsequent layers.

### Project file & Debug log uploads

[FanSpeedLayerChangeIssue.3mf.zip](https://github.com/user-attachments/files/17450875/FanSpeedLayerChangeIssue.3mf.zip)

### Checklist of files to include

- [x] Log file
- [X] Project file

### Anything else?

Nasty bug that's hard to notice unless you happen to look at the fan speed preview!

### PR DESCRIPTION
**Pull request by Noisyfox**
This fixes #7171
Fna mover now manipulate part cooling fans only and ignore all other fans (which is what it's designed for).

### CODE REVIEW

**Comment by psiberfunk** [comment]
@Noisyfox  does this fully fix #7171  ?  It seems to only address the fan itself, but not mis-attributing the cooling layer time calculation to the layer after the change rather than the one before, which is the appropriate one.

**Comment by Noisyfox** [comment]
> @Noisyfox does this fully fix #7171 ? It seems to only address the fan itself, but not mis-attributing the cooling layer time calculation to the layer after the change rather than the one before, which is the appropriate one.

Only the first half. The cooling layer is a different issue and will be addressed in its own PR.

File: src/libslic3r/GCode/FanMover.cpp [hunk 1]
```diff
@@ -83,6 +87,12 @@ int16_t get_fan_speed(const std::string &line, GCodeFlavor flavor) {
         if (flavor == (gcfMach3) || flavor == (gcfMachinekit)) {
             return (int16_t)get_axis_value(line, 'P');
         } else {
+            // BBS: for Bambu machine, we both use M106 P1 and M106 to indicate the part cooling fan
```
Comment (SoftFever) [inline src/libslic3r/GCode/FanMover.cpp:90]: Since we support not just Bambu machines, ref to: https://github.com/SoftFever/OrcaSlicer/wiki/Auxiliary-fan and https://github.com/SoftFever/OrcaSlicer/wiki/air-filtration.
Would it be better to update the comment here to reduce confusion?

Comment (psiberfunk) [reply src/libslic3r/GCode/FanMover.cpp:90]: well.. it's nice to know this part of the code came from bambuslicer, no ? also it's not an untrue statement.. it may also be true for other printers as well, but this one explicitly says what the case is for that one.

Comment (SoftFever) [reply src/libslic3r/GCode/FanMover.cpp:90]: > well.. it's nice to know this part of the code came from bambuslicer, no ? also it's not an untrue statement.. it may also be true for other printers as well, but this one explicitly says what the case is for that one.

This is not true. This feature was ported into OrcaSlicer from SuperSlicer by @scottmudge at PR https://github.com/SoftFever/OrcaSlicer/pull/910

> it may also be true for other printers as well, but this one explicitly says what the case is for that one.

I'm unsure of what point you're trying to make. This feature is not specific to Bambu machines; Orca supports the use of M106 P1 and M106 commands for the part cooling fan on all printers, which is the basis for my previous comment.

Comment (psiberfunk) [reply src/libslic3r/GCode/FanMover.cpp:90]: oh, well nevermind then.

Comment (Noisyfox) [reply src/libslic3r/GCode/FanMover.cpp:90]: https://github.com/SoftFever/OrcaSlicer/blob/ae31f4fb1fd42eab674008145c187b76faad7560/src/libslic3r/GCode/GCodeProcessor.cpp#L3934

FYI I copied this from here.

**Comment by psiberfunk** [comment]
@SoftFever I know this didn't quite make it into 2.2.0 , and while I technically have permission to approve it, I feel like I probably shouldn't :). It does appear to be OK to me though.

File: src/libslic3r/GCode/FanMover.cpp (hunk 1 above)
Comment (Noisyfox) [reply src/libslic3r/GCode/FanMover.cpp:90]: The problem is that BambuLab uses P1 as the part cooling fan, not P0, which is what this check really meant for (because we don't check for P0).

**Review by SoftFever — APPROVED** [review]

**Review by SoftFever — APPROVED** [review]
LGTM
Thank you
