### PR TITLE
Reduce artifacts from short travel moves before external perimeters

### LINKED ISSUE #11208: The acceleration of short movements does not match the acceleration of the outer wall
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.1

### Operating System (OS)

Windows

### OS Version

11

### Additional system information

_No response_

### Printer

Bambu lab p2s

### How to reproduce

Switch to detailed gcode in the slicer and you will see that the acceleration of short movements is equal to the acceleration of default movements

### Actual results

All improvements and positive aspects were described in PR [#10722](https://github.com/SoftFever/OrcaSlicer/pull/10722)

### Expected results

Improving print quality by eliminating defects caused by very short movements just before the outer perimeters

### Project file & Debug log uploads

...

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kisslorand**
# Description

This PR improves print quality by addressing artifacts caused by very short travel moves immediately before external perimeters. The idea originates from PrusaSlicer, and the approach here builds on tests from PR #10643. These tiny moves no longer inherit high travel acceleration, which can otherwise introduce vibrations and surface imperfections at the seam.

The solution applies the same acceleration and jerk values as the external perimeter to those short moves. This eliminates unnecessary bursts of motion, prevents artifacts, and preserves seam quality.

The change is internal and automatic — no user settings or preset adjustments are required. It assumes a well-tuned printer configuration (accel, speed, input shaping, PA, SCV, jerk, etc.), which naturally depends on the firmware/OS in use (Klipper, RepRap, Marlin, etc.).

Benefits:
- Eliminates vibrations/artifacts at external perimeter starts.
- Maintains seam quality and external surface smoothness.
- Requires no user intervention or preset changes.

## Tests

Compiled locally and printed many rectangular and cylindrical objects like these (but not only):

Fixes #11208

### CODE REVIEW

File: src/libslic3r/GCode.cpp [hunk 1]
```diff
@@ -6061,21 +6061,37 @@ std::string GCode::travel_to(const Point& point, ExtrusionRole role, std::string
...
             acceleration_to_set = (unsigned int) floor(m_config.initial_layer_acceleration.value + 0.5);
         }
+        
         if (m_config.default_jerk.value > 0 && m_config.initial_layer_jerk.value > 0) {
             jerk_to_set = m_config.initial_layer_jerk.value;
         }
     } else {
-        if (m_config.default_acceleration.value > 0 && m_config.travel_acceleration.value > 0) {
-            acceleration_to_set = (unsigned int) floor(m_config.travel_acceleration.value + 0.5);
+        if (m_config.default_acceleration.value > 0) {
```
Comment (RF47) [inline src/libslic3r/GCode.cpp:6074]: Can we support junction deviation?
```cpp
if (m_config.default_acceleration.value > 0 || m_config.default_junction_deviation.value > 0) {
```

**Comment by igiannakas** [comment]
This is an interesting take indeed. External perimeter acceleration should indeed work nicely for the smaller travel moves.

I do wonder what test results did Prusa have to indicate that a slower acceleration for the external perimeter travel was beneficial vs an approach like this which is much simpler (and consistent).

**Comment by kisslorand** [comment]
They most probably miss your eagle eyes that saw the regression on the seams on curved surfaces.

@RF47 
I am eagerly waiting for you to test this too.

**Comment by RF47** [comment]
It seems to work well, correctly setting the acceleration for print and travel.
image
image

I am curious to see how it compares to Prusa Slicer:
image
image
I don't know if something is configured incorrectly, but it seems that short travel acceleration is not being used in prusa slicer (external perimeter acceleration is used, as in this implementation).

in this prusa comit:
https://github.com/prusa3d/PrusaSlicer/commit/52f521901f7d68027a3b66fc4acd8b9d225fc6d7#diff-cb3d09d2073b6e9032c65d07aa8f10d166324a53136b2aa1288f7b76f7d94319

i found this comment:
```cpp
    if (!GCodeWriter::supports_separate_travel_acceleration(config().gcode_flavor)) {
        // In case that this flavor does not support separate print and travel acceleration,
        // reset acceleration to default.
        // TODO: This doesn't seem to perform what the comment describes.
        gcode += this->m_writer.set_travel_acceleration(travel_acceleration);
    }
```
maybe that's my case.

**Comment by PawiX25** [comment]
When this will be merged?

**Comment by boromyr** [comment]
What happens if the travel acceleration is less than that of the outer wall?
Furthermore, could it be useful to further reduce the displacement acceleration when movements occur inside the model and are not required to cross an external perimeter? In a test I ran in a cube, drastically reducing the travel acceleration completely suppressed the vibrations at the start of the perimeter.

**Comment by igiannakas** [comment]
What is a displacement acceleration?

> What happens if the displacement acceleration is less than that of the outer wall? Furthermore, could it be useful to further reduce the displacement acceleration when movements occur inside the model and are not required to cross an external perimeter? In a test I ran in a cube, drastically reducing the displacement acceleration completely suppressed the vibrations at the start of the perimeter.

**Comment by boromyr** [comment]
Error in translation. I corrected the previous message

**Comment by kisslorand** [comment]
> What happens if the travel acceleration is less than that of the outer wall?

Highly improbable, why would you have travel acceleration lower than any print acceleration?

> Furthermore, could it be useful to further reduce the displacement acceleration when movements occur inside the model and are not required to cross an external perimeter? In a test I ran in a cube, drastically reducing the travel acceleration completely suppressed the vibrations at the start of the perimeter.

Reduced acceleration before the outer wall affects the seam quality as already proven (more evident for seams on a round wall).


The whole idea is that you already have an acceleration set that will be used for the outer wall. If that is good enough for the outer wall (that might have tiny segments also) it must be just as good for the tiny travel towards the outer wall.

**Comment by puffofsmoke** [comment]
- If the "Wipe Before External Loop" option is enabled, we have two sections of travel near the beginning of the external loop. Both paths affected by decreased acceleration. Fine!

{7D6856F3-2442-4D89-AAA8-6FE4CFFA152C}

- In contrast, "Wall printing order" can be set to "outer/ inner" and we can have more than one object with the "Wipe Before External Loop" option enabled or disabled. This pach doing nothing in this case and question is what to do.

- The same with "Wall printing order" set to "outer/ inner", "Print Infill First" enabled and "Wipe Before External Loop" enabled or disabled.


- And the funniest thing is that without this path, the "Wipe before external loop" option will always add a short move before the external perimeter and reduce the acceleration to the external wall acceleration **before** this move occurs.

Technically, we already have a better setting that in any case will add a short movement in front of the outer perimeter and it will happen with the acceleration of the outer perimeter.

File: src/libslic3r/GCode.cpp [hunk 2]
```diff
@@ -6067,21 +6067,37 @@ std::string GCode::travel_to(const Point& point, ExtrusionRole role, std::string
...
+            if (role == erExternalPerimeter && travel.length() < scale_(EXTRUDER_CONFIG(retraction_minimum_travel))) {
+                if (m_config.outer_wall_acceleration.value > 0)
+                    acceleration_to_set = (unsigned int) floor(m_config.outer_wall_acceleration.value + 0.5);
```
Comment (valerii-bokhan) [inline src/libslic3r/GCode.cpp:6867]: The case if `outer_wall_acceleration <= 0` shold also be handled (just in case).

Something like:
```suggestion
                if (m_config.outer_wall_acceleration.value > 0) {
                    acceleration_to_set = (unsigned int) floor(m_config.outer_wall_acceleration.value + 0.5);
                } else if (m_config.travel_acceleration.value > 0) {
                    acceleration_to_set = (unsigned int) floor(m_config.travel_acceleration.value + 0.5);
                }
```

File: src/libslic3r/GCode.cpp [hunk 3]
```diff
@@ -6067,21 +6067,37 @@ std::string GCode::travel_to(const Point& point, ExtrusionRole role, std::string
...
+                    acceleration_to_set = (unsigned int) floor(m_config.travel_acceleration.value + 0.5);
+            }
         }
-        if (m_config.default_jerk.value > 0 && m_config.travel_jerk.value > 0) {
-            jerk_to_set = m_config.travel_jerk.value;
+
+        if (m_config.default_jerk.value > 0) {
+            if (role == erExternalPerimeter && travel.length() < scale_(EXTRUDER_CONFIG(retraction_minimum_travel))) {
+                if (m_config.outer_wall_jerk.value > 0)
+                    jerk_to_set = m_config.outer_wall_jerk.value;
```
Comment (valerii-bokhan) [inline src/libslic3r/GCode.cpp:6877]: Same thing as above:
```suggestion
                if (m_config.outer_wall_jerk.value > 0) {
                    jerk_to_set = m_config.outer_wall_jerk.value;
                } else if (m_config.travel_jerk.value > 0) {
                    jerk_to_set = m_config.travel_jerk.value;
                }
```

File: src/libslic3r/GCode.cpp (hunk 2 above)
Comment (kisslorand) [reply src/libslic3r/GCode.cpp:6867]: It's handled by the `else if`.

File: src/libslic3r/GCode.cpp (hunk 3 above)
Comment (kisslorand) [reply src/libslic3r/GCode.cpp:6877]: See above

File: src/libslic3r/GCode.cpp (hunk 2 above)
Comment (valerii-bokhan) [reply src/libslic3r/GCode.cpp:6867]: > It's handled by the `else if`.

But the `else if` goes for `role == erExternalPerimeter && travel.length() < scale_(EXTRUDER_CONFIG(retraction_minimum_travel))`

```
        if (m_config.default_acceleration.value > 0) {
            if (role == erExternalPerimeter && travel.length() < scale_(EXTRUDER_CONFIG(retraction_minimum_travel))) {

                if (m_config.outer_wall_acceleration.value > 0)
                    acceleration_to_set = (unsigned int) floor(m_config.outer_wall_acceleration.value + 0.5);
                --> the `else` is missing here, if `outer_wall_acceleration` is 0, nothing will be set

            } else {
                if (m_config.travel_acceleration.value > 0)
                    acceleration_to_set = (unsigned int) floor(m_config.travel_acceleration.value + 0.5);
            }
        }
```

Comment (kisslorand) [reply src/libslic3r/GCode.cpp:6867]: You pasted a different code here than above.

Comment (valerii-bokhan) [reply src/libslic3r/GCode.cpp:6867]: I should have selected the whole `if (m_config.default_acceleration.value > 0)` block, sorry about that.

Comment (kisslorand) [reply src/libslic3r/GCode.cpp:6867]: OK.
The else is missing by design. If "Outer wall acceleration" is set to 0 by the user it means the user is happy with the results how Orca assigns acceleration to outer walls. The lack of `else` will assign to the tiny travel before the external loop the same acceleration as for the outer wall, exactly as wanted, to have the same acceleration for the tiny travels before the external loop as it is for the outer wall itself.
I hope this clears it.

**Comment by PawiX25** [comment]
Could we please get this merged? I am experiencing significant quality issues in OrcaSlicer compared to PrusaSlicer on models with small features/islands

The difference is drastic. In OrcaSlicer, I am getting severe artifacts (visible and inconsistent layer lines) and blobs on the external perimeters (specifically on the antlers in the example below), whereas PrusaSlicer handles them perfectly. It looks to me that the current acceleration handling for short travels is causing these defects.


PrusaSlicer: 
Screenshot 2025-11-19 015828
OrcaSlicer: 
Screenshot 2025-11-19 020107

The issues on the print (sliced by Orca, doesn't happen on PrusaSlicer)
image
image

**Comment by SoftFever** [comment]
> Could we please get this merged? I am experiencing significant quality issues in OrcaSlicer compared to PrusaSlicer on models with small features/islands
> 
> The difference is drastic. In OrcaSlicer, I am getting severe artifacts (visible and inconsistent layer lines) and blobs on the external perimeters (specifically on the antlers in the example below), whereas PrusaSlicer handles them perfectly. It looks to me that the current acceleration handling for short travels is causing these defects.
> 
> PrusaSlicer: Screenshot 2025-11-19 015828 OrcaSlicer: Screenshot 2025-11-19 020107
> 
> The issues on the print (sliced by Orca, doesn't happen on PrusaSlicer) image image

Hi @PawiX25 
Thank you for showing picture.
Is the improvement in your case due to the `Travel short distance acceleration` option in PS?  
Did you enable that option in PS?

**Review by SoftFever — APPROVED** [review]
This is an elegant solution. Thank you.

**Comment by PawiX25** [comment]
Yes, I have Travel short distance acceleration enabled and set to 250 mm/s² in PrusaSlicer.

To rule out any hardware issues, I went through extensive troubleshooting with Prusa Support. I replaced belts, retightened everything, and completely reassembled the pulleys. Prusa Support then sent me a G-code file sliced in PrusaSlicer to test, and it printed absolutely flawlessly.

Currently, everything I slice in PrusaSlicer prints perfectly with no defects, whereas OrcaSlicer still produces these artifacts on the exact same hardware.

I’ve attached photos below showing the issues in Orca
PXL_20251110_191358167 (1)
PXL_20251110_191358167 (1)
PXL_20251019_202538011
PXL_20251017_050627739 MP
PXL_20251017_050615962 MP
PXL_20251016_174948047
PXL_20251016_002853493
PXL_20251016_002846504
PXL_20251016_002844176

**Comment by igiannakas** [comment]
Is this with this PR or without?

**Comment by PawiX25** [comment]
These photos show the issues I have in Orca without this PR

**Comment by valerii-bokhan** [comment]
Can you please share photos with the PR to show the "before/after" difference?

**Comment by PawiX25** [comment]
Sure, I am compiling the build with this PR right now. I'll print the model i was trying to print before as soon as it finishes and post the before/after photos.

**Comment by igiannakas** [comment]
Also please ensure cooling and movement parameters are identical, including slicing resolution. Just a double check as some of the above artefacts are not appearing as ringing related but have similarities to slicing tolerance and cooling artefacts I’ve encountered before :)
