### PR TITLE
Don't steal focus from text inputs on mouse

### LINKED ISSUE #12823: [2.3.2-dev] Selection in sidebar removed when mouse moves out of sidebar
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.2-dev

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

Any

### How to reproduce

1. Select something in the sidebar
Image

2. Move mouse out of sidebar
Image
 
3. It's deselected
Image

### Anything else?

Very annoying behavior that messes with muscle memory. Wasn't a thing in builds a few weeks ago, it's a recent regression

### PR DESCRIPTION
**Pull request by RF47**
# Description

This fix a bug introduced in  382cf57166deac2a466f225311dc4575ecd11780
When moving the mouse over the 3D viewport, the focus was lost on the selected text.

Fix #12823

### CODE REVIEW

File: src/slic3r/GUI/GLCanvas3D.cpp [hunk 1]
```diff
@@ -4263,7 +4263,13 @@ void GLCanvas3D::on_mouse(wxMouseEvent& evt)
                 p = p->GetParent();
             auto *top_level_wnd = dynamic_cast<wxTopLevelWindow*>(p);
             //Orca: Set focus so hotkeys like 'tab' work when a notification is shown.
-            if (top_level_wnd != nullptr && top_level_wnd->IsActive())
+            // But don't steal focus from text input controls (fixes deselection bug when mouse leaves window)
+            wxWindow* focused = wxWindow::FindFocus();
+            bool focus_in_text_ctrl = focused != nullptr &&
+                (dynamic_cast<wxTextCtrl*>(focused) != nullptr ||
```
Comment (yw4z) [inline src/slic3r/GUI/GLCanvas3D.cpp]: wxTextCtrl, wxComboBox, wxSpinCtrl not in use. currently that should be TextInput, ComboBox, SpinInput

Comment (yw4z) [reply src/slic3r/GUI/GLCanvas3D.cpp]: TextInput and SpinInput based on wxTextCtrl but not sure thats the control handles focus
ComboBox also based on TextInput

Comment (RF47) [reply src/slic3r/GUI/GLCanvas3D.cpp]: I think this is working, but don’t hesitate to comit changes, you’re the expert.

Comment (yw4z) [reply src/slic3r/GUI/GLCanvas3D.cpp]: then wxTextCtrl should be enough for all controls since all controls based on it

Comment (RF47) [reply src/slic3r/GUI/GLCanvas3D.cpp]: i will test it

Comment (RF47) [reply src/slic3r/GUI/GLCanvas3D.cpp]: you are right

**Comment by yw4z** [comment]
LGTM thanks
