### PR TITLE
Fix crash in printer config when switching tabs

### LINKED ISSUE #6486: v2.2 Nightly Dev's crashing when editing (custom) Printer Settings
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0-dev

### Operating System (OS)

Windows

### OS Version

Win10

### Additional system information

_No response_

### Printer

Ender 3 v2

### How to reproduce

Open a recent (August 13 or 14) 2.2.0-dev portable Nightly.
Change some text in Printer settings>Machine G-code. Or change or add to a Note.
Click away to another tab in Printer settings.

### Actual results

Crash in WIn10.
Sometimes Windows displays a message about a memory problem.

### Expected results

In the past I have edited my Printer settings without issue. This problem just started.

### Project file & Debug log uploads

[Orca crash log.zip](https://github.com/user-attachments/files/16646775/Orca.crash.log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Anything else?

Okay, when I see Windows report a memory problem, it could be my RAM. I will run a Diagnostic after posting here.
If it's not a RAM problem on my end, it looks like this started with v2.2.0. (I just now tried an August 8 Nightly. Same behavior.)
I just now tried v2.2.1-portable. It does not crash when editing the same Printer Setting.

### PR DESCRIPTION
**Pull request by Noisyfox**
This fixes #6486

### CODE REVIEW

**Comment by Noisyfox** [comment]
Some explainations:
e139fd18f297062e1ff94cf4e2cb545c
See the upper call stack. When switching tabs after updating any values, the tab's button's event handler will trigger a refreshing of the printer config screen, which will call `DeleteAllItems`, which will delete the tab button that's currently running the eventhandler, that causes this use-after-free crash.

This PR updates the tab buttons in place and avoid destroying buttons when uncessary.

File: src/slic3r/GUI/PartPlate.cpp [hunk 1]
```diff
@@ -470,7 +470,7 @@ void PartPlate::calc_gridlines(const ExPolygon& poly, const BoundingBox& pp_bbox
 	int count = 0;
 	int step  = 10;
 	// Orca: use 500 x 500 bed size as baseline.
-    auto      grid_counts = pp_bbox.size() / ((coord_t) scale_(step * 50));
+    const Point grid_counts = pp_bbox.size() / ((coord_t) scale_(step * 50));
```
Comment (Noisyfox) [inline src/slic3r/GUI/PartPlate.cpp:473]: This line caused false address sanitizer exceptions that prevented me from debugging the real poblem so I fixed this. Doesn't really related to the crash though.

**Review by SoftFever — APPROVED** [review]
Tested, no more crashes and switching from single tool to multi tool machine works fine as well.
Thank you!
