### PR TITLE
Fix M141 S0 at end of gcode

### LINKED ISSUE #2306: An M141 S0 appear at the end of the gcode no matter what your printer is (1.8.0-dev)
### OrcaSlicer Version

1.8.0-dev

### OS version

Windows OS

### Additional system information

_No response_

### Printer

FLSUN V400

### How to reproduce

Just slice any model.

### Actual results

imagen

### Expected results

The M141 must not be there

### Project file & Debug log uploads

Not necessary

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### PR DESCRIPTION
**Pull request by Ocraftyone**
fixes #2306 where gcode to turn off chamber heating is hardcoded into the slicer. BBS has also removed this line of code in their source.

### CODE REVIEW

**Comment by discip** [comment]
@Ocraftyone
If you want this PR to automatically close the corresponding issue you have to put it like that:
**fixes #2306** (without _`issue`_ in between) [GitHub Docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) 😊

File: src/libslic3r/GCode.cpp [hunk 1]
```diff
@@ -2558,9 +2558,6 @@ void GCode::_do_export(Print& print, GCodeOutputStream &file, ThumbnailsGenerato
     file.write(m_writer.update_progress(m_layer_count, m_layer_count, true)); // 100%
     file.write(m_writer.postamble());
 
-    file.write(m_writer.set_chamber_temperature(0, false));  //close chamber_temperature
```
Comment (SoftFever) [inline src/libslic3r/GCode.cpp:2561]: I plan to rewrite this part in the future.
For now, can you use support_chamber_temp_control to check whether we need turn off chamber heater instead of deleting it?

**Review by SoftFever — CHANGES_REQUESTED** [review]

**Comment by Ocraftyone** [comment]
I looked through the gui and searched the project and only found one mention of support_chamber_temp_control, so I have it so that it will disable the heated chamber either if the support chamber temp flag is thrown or if the chamber temp was set above 0

**Review by SoftFever — APPROVED** [review]

**Comment by SoftFever** [comment]
LGTM
Thanks for fixing the issue.
