### PR TITLE
Fix: Correcting the behavior of the camera panning.

### LINKED ISSUE #11107: Camera panning is not working correctly
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.2-dev

### Operating System (OS)

Windows

### OS Version

All

### Additional system information

_No response_

### Printer

All

### How to reproduce

- Create an empty project with multiple plates, each added with a generic cube (optional).
- Try to select plates, rotate, and pan the camera.

Image

The situation gets worse if there are several plates.

### Actual results

Sometimes it works fine (camera "follows" the mouse cursor very fast), but then it pans really "viscously" after rotating the scene by 180 degrees.

### Expected results

The camera pans quickly, similar to the first half of the GIF attached to this issue.

### Project file & Debug log uploads

None.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

This issue also exists in BBS.

### PR DESCRIPTION
**Pull request by valerii-bokhan**
# Description

Fixes #11107

### Before:

camera_pan_bug

### After:

camera_pan_fix

### CODE REVIEW

File: src/slic3r/GUI/GLCanvas3D.cpp [hunk 1]
```diff
@@ -4403,10 +4403,8 @@ void GLCanvas3D::on_mouse(wxMouseEvent& evt)
         else if (is_camera_pan(evt, swap_mouse_buttons)) {
             // if dragging with right button or if button functions swapped and dragging with left button over blank area then pan
             if (m_mouse.is_start_position_2D_defined()) {
-                // get point in model space at Z = 0
-                float z = 0.0f;
-                const Vec3d& cur_pos = _mouse_to_3d(pos, &z);
-                Vec3d orig = _mouse_to_3d(m_mouse.drag.start_position_2D, &z);
+                const Vec3d& cur_pos = _mouse_to_3d(pos, nullptr);
```
Comment (valerii-bokhan) [inline src/slic3r/GUI/GLCanvas3D.cpp]: By using `nullptr` as a parameter value I wanted the `_mouse_to_3d` function to use the ray casting approach instead of  `igl::unproject` method. Because ray casting works way better in this case.

File: src/slic3r/GUI/GLCanvas3D.cpp [hunk 2]
```diff
@@ -4424,6 +4422,7 @@ void GLCanvas3D::on_mouse(wxMouseEvent& evt)
 
             m_camera_movement = true;
             m_mouse.drag.start_position_2D = pos;
+            m_mouse.drag.move_start_threshold_position_2D = pos;
```
Comment (valerii-bokhan) [inline src/slic3r/GUI/GLCanvas3D.cpp:4694]: This line was missing. I ported it from BBS.

**Comment by valerii-bokhan** [comment]
I understand that it does not fix the actual issue (the "math" looks wrong in `GLCanvas3D::_mouse_to_3d`), as I wanted the fix to be as simple as possible.

But the problem should be revisited appropriately, as it might cause more bugs than we can expect.

**Comment by Noisyfox** [comment]
Were you using perspective view or orthographic? I noticed some fix on PrusaSlicer regarding the issue of `_mouse_to_3d` in perspective mode.


https://github.com/prusa3d/PrusaSlicer/blame/f1776c0a6347bb84986d10eac8db1021f5bd8548/src/slic3r/GUI/GLCanvas3D.cpp#L7265

**Comment by valerii-bokhan** [comment]
Hey, I use a Perspective View, but let me port and test the fix for the Orthographic View as well.

**Comment by Noisyfox** [comment]
Ah sorry, I mean perspective view. I think the old code works properly in orthographic view. So what PS did is force using orthographic view when calculating the panning by setting `use_ortho=true`:

https://github.com/prusa3d/PrusaSlicer/blob/f1776c0a6347bb84986d10eac8db1021f5bd8548/src/slic3r/GUI/GLCanvas3D.cpp#L4085-L4086

**Comment by Noisyfox** [comment]
BTW, should we also update this place too?

https://github.com/SoftFever/OrcaSlicer/blob/d87f8e3a88f1116c650744980033289e9d335783/src/slic3r/GUI/GLCanvas3D.cpp#L3932-L3939

**Comment by valerii-bokhan** [comment]
> So what PS did is force using orthographic view when calculating the panning by setting `use_ortho=true`

I just wanted to mention it. It looks really odd tbh.

`if (use_ortho && type != Camera::EType::Ortho)` looks weird - use ortho math for non-ortho view...

**Comment by valerii-bokhan** [comment]
> BTW, should we also update this place too?

By the way, yes, it makes sense, but I don't know how to test it properly.

**Comment by valerii-bokhan** [comment]
I will do all the tests again for both the views, but I think it's better not to port PS changes. I will explain later today.

**Comment by Noisyfox** [comment]
I think we should use ortho view anyway because we don't want the distance to affect our panning.

**Comment by valerii-bokhan** [comment]
> I think we should use ortho view anyway.

Do you mean using the ortho logic approach from PS for the perspective view?

> because we don't want the distance to affect our panning

I am sorry, I don't get this part probably. I tested this approach a lot and it works the best in my opinion.

Anyway, I plan to record my screen later today to showcase all the solutions we have. Then we can continue the discussion.

**Comment by valerii-bokhan** [comment]
Showcase of the current fix (from this PR) (a depth buffer value; ray casting).

See how cylinders "follow" the mouse cursor.

### Perspective:
camera_pan_fix_1

### Orthographic:
camera_pan_fix_2

**Comment by valerii-bokhan** [comment]
Showcase of the fix that was ported from the Prusa Slicer (creating a custom Orthographic Projection matrix).

See how cylinders "follow" the mouse cursor.

### Perspective:

camera_pan_fix_3

### Orthographic:

camera_pan_fix_4

**Comment by valerii-bokhan** [comment]
@Noisyfox, as you can see, the Orthographic view works well, but Perspective is problematic.

In my opinion, the results of my fix look better. But if we don't trust the depth buffer or the ray-casting method, I can try to fix the math in the Prusa Slicer fix.

**Comment by Noisyfox** [comment]
> In my opinion, the results of my fix look better.

Yeah I agree yours looks much better. Though another question: since your fix relys on ray caster, what would happen if cursor does not hover over anything (bed, object, buttons etc)? In this case the ray caster won't hit anything and it will fallback to the old method right? Which will then be problematic again.

**Comment by valerii-bokhan** [comment]
Okay, then I have to fix the math of the `_mouse_to_3d` function.

**Comment by valerii-bokhan** [comment]
@Noisyfox Hey! I have found the fancy `CameraUtils` class in the project. It helped me to fix the issue pretty quickly.

camera_panning

File: src/slic3r/GUI/GLCanvas3D.cpp [hunk 3]
```diff
@@ -9372,16 +9374,15 @@ Vec3d GLCanvas3D::_mouse_to_3d(const Point& mouse_pos, float* z)
...
+        const SceneRaycaster::HitResult hit = m_scene_raycaster.hit(mouse_pos.cast<double>(), camera, nullptr);
         return hit.is_valid() ? hit.position.cast<double>() : _mouse_to_bed_3d(mouse_pos);
     }
     else {
-        const Camera& camera = wxGetApp().plater()->get_camera();
-        const Vec4i32 viewport(camera.get_viewport().data());
-        Vec3d out;
-        igl::unproject(Vec3d(mouse_pos.x(), viewport[3] - mouse_pos.y(), *z), camera.get_view_matrix().matrix(), camera.get_projection_matrix().matrix(), viewport, out);
-        return out;
+        Vec2d position = CameraUtils::get_z0_position(camera, Vec2d(mouse_pos.x(), mouse_pos.y()));
```
Comment (valerii-bokhan) [inline src/slic3r/GUI/GLCanvas3D.cpp:9385]: This utility function handles all the `unproject` stuff correctly under the hood for both projection types, then it applies additional math transformations for `Z = 0`.

I also need to investigate whether these additional transformations are required when `Z != 0`, but maybe in a separate PR.

**Comment by valerii-bokhan** [comment]
I have found a bug that needs to be fixed.

**Comment by Noisyfox** [comment]
I noticed a bug that if you panning up & down when looking from the side, the plate will move in & out instead:
panning


I'm going to revert this for now.
