### PR TITLE
FIX: Open provided file at startup

### LINKED ISSUE #11438: macOS: 3mf project files closing immediately when opened from Finder
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.2-dev (3a7309a)

### Operating System (OS)

macOS

### OS Version

26.1 (25B78)

### Additional system information

CPU: M3 Max
Memory: 128 GB

### Printer

Bambu Lab H2D

### How to reproduce

1. With OrcaSlicer.app closed, open a 3mf project file from the Finder (either with .3mf set to open with OrcaSlicer by default, or by right-clicking and selecting Open With –> OrcaSlicer.app
2. Wait for OrcaSlicer to launch and open the 3mf project file

### Actual results

The project file loads, displays in the Prepare tab's preview momentarily, and then the view reverts to a blank build plate with the project file no longer open (as validated from the Project tab).

### Expected results

The project opens normally and can be previewed, sliced, and printed.

### Project file & Debug log uploads

[one-rupee_orcatest.3mf.zip](https://github.com/user-attachments/files/23684520/one-rupee_orcatest.3mf.zip)

[debug_Fri_Nov_21_13_24_38_2122.log.0.zip](https://github.com/user-attachments/files/23684522/debug_Fri_Nov_21_13_24_38_2122.log.0.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

### Anything else?

Screen recording of issue:  https://github.com/user-attachments/assets/a81f664d-7fd8-4e85-804e-4679137aff52

Opening project files from File –> Open Project... is _not_ affected by this issue — only opening them from the Finder. 

This does not appear to be a permissions-related issue as the project file does initially load and display before closing, and additionally, OrcaSlicer.app has been granted Full Disk Access permissions in System Settings –> Privacy & Security.

### PR DESCRIPTION
**Pull request by kisslorand**
Opening OrcaSlicer by double-clicking an STL/3MF (or sending a model from Fusion360) caused the model to appear for a split second and then vanish, leaving an empty build plate.

This regression came from porting [a change](https://github.com/kisslorand/OrcaSlicer/commit/7eaabc485660a26e19ecbb63c1e7ef9e92f27473) from Bambu Studio. The fix was correct for their codebase, but since OrcaSlicer doesn't have that issue, bringing it over ended up causing startup files to be ignored.

This PR restores the correct behavior:
 - If OrcaSlicer is launched with a file, that file now loads and stays visible.
 - If OrcaSlicer is launched without a file, the normal “restore previous project” behavior still works.

This makes file-based launching reliable again.

Fixes #11438

### CODE REVIEW

**Comment by NanashiTheNameless** [comment]
Confirmed: error reproduced!

File: src/slic3r/GUI/GUI_App.cpp [hunk 1]
```diff
@@ -821,13 +821,14 @@ void GUI_App::post_init()
 
         BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", init with input files, size %1%, input_gcode %2%")
             %this->init_params->input_files.size() %this->init_params->input_gcode;
+
+        switch_to_3d = true;
```
Comment (Noisyfox) [inline src/slic3r/GUI/GUI_App.cpp:825]: Just to double check, this one dose not change any existing behavior right? Just to reduce code dup?

Comment (kisslorand) [reply src/slic3r/GUI/GUI_App.cpp:825]: Yes, that's the sole purpose.

**Comment by Noisyfox** [comment]
I think what's better option is to cherrypick this change instead: 
https://github.com/bambulab/BambuStudio/commit/ad29815098eba53178b13f53f3514dd47ad3a51a

Otherwise when you opening files the unsaved previous project will vanish silently.

**Comment by kisslorand** [comment]
Just tested and the project is not overwritten, the opened object is added to the existing one or existing ones, just as it was before, just as it feels natural.
The suggested commit cannot be cherry-picked as in Orca 'is_empty_project' is not a member of 'Slic3r::GUI::Plater'.

Anyway it feels awkward to try to restore a previous project when you explicitly open Orca with a specific file in mind...

**Comment by Noisyfox** [comment]
> Anyway it feels awkward to try to restore a previous project when you explicitly open Orca with a specific file in mind...

But that gives the user the last chance to restore an unsaved project if he/she accidentally double clicked a 3mf file instead of the orca app shortcut after an app crash/power lost etc.

**Comment by Glod76** [comment]
I’m having the same problem—when I open a 3MF file or stl from Windows Explorer, it appears for a split second and then disappears. it disappeared when the bed zooms in and centers

**Comment by kisslorand** [comment]
> I think what's better option is to cherrypick this change instead: [bambulab/BambuStudio@ad29815](https://github.com/bambulab/BambuStudio/commit/ad29815098eba53178b13f53f3514dd47ad3a51a)
> 
> Otherwise when you opening files the unsaved previous project will vanish silently.

Done

File: src/slic3r/GUI/Plater.hpp [hunk 2]
```diff
@@ -350,6 +350,7 @@ class Plater: public wxPanel
         m_exported_file = exported_file;
     }
 
+    bool Plater::is_empty_project();
```
Comment (Noisyfox) [inline src/slic3r/GUI/Plater.hpp]: `Plater::` should be removed

Comment (kisslorand) [reply src/slic3r/GUI/Plater.hpp]: Yup, you're right. Done.
