### PR TITLE
Fix an issue that only 1 bottom/top will be generated when ensure vertical thickness is set to None

### LINKED ISSUE #4474: Ensure Vertical Shell Thickness = None, causes Only 1 Top / Bottom Layer
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0-Beta

### Operating System (OS)

Windows

### OS Version

Windows 10 22H2

### Additional system information

_No response_

### Printer

Voron 2.4

### How to reproduce

1. Import Model
2. Turn on "Alternate Extra Wall" or manually set "Ensure Vertical Shell Thickness" to "None"
3. Slice

### Actual results

The sliced Model has only 1 Top & 1 Bottom Layer. No matter how many Top or Bottom Layers are selected and set, or what Shell Thickness is specified. Seems like the "Ensure Vertical Shell Thickness" being set to "None" overrides the Top/Bottom Shells setting entirely. This makes the "Alternate Extra Walls" function inoperable as it cannot be enabled without also setting "Ensure Vertical Shell Thickness" to None.
Alternate_01

### Expected results

"Ensure Vertical Shell Thickness" shouldn't override Top & Bottom Layer settings, just the "Top/Bottom Shell Thickness" setting.
Alternate_02
 

### Project file & Debug log uploads

[Ensure_Vertical_Shell_Thickness_02.zip](https://github.com/SoftFever/OrcaSlicer/files/14595137/Ensure_Vertical_Shell_Thickness_02.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SoftFever**
image

Fixes #4474

### CODE REVIEW

File: src/libslic3r/PrintObject.cpp [hunk 1]
```diff
@@ -3271,32 +3271,38 @@ void PrintObject::discover_horizontal_shells()
...
                         // the amount of solid infill on walls. However reduce the margin to 20% overhang
                         // as we want to generate infill on sloped vertical surfaces but still keep a small amount of
                         // filtering. This is an arbitrary value to make this option safe
                         // by ensuring that top surfaces, especially slanted ones dont go **completely** unsupported
                         // especially when using single perimeter top layers.
-                        float margin = region_config.ensure_vertical_shell_thickness.value == evstCriticalOnly? float(neighbor_layerm->flow(frExternalPerimeter).scaled_width()) * 0.2f : float(neighbor_layerm->flow(frExternalPerimeter).scaled_width());
-                        Polygons too_narrow = diff(
-                            new_internal_solid,
-                            opening(new_internal_solid, margin, margin + ClipperSafetyOffset, jtMiter, 5));
+                        float    margin     = float(neighbor_layerm->flow(frExternalPerimeter).scaled_width()) * factor;
```
Comment (SoftFever) [inline src/libslic3r/PrintObject.cpp:3293]: @igiannakas 
I've identified a potential issue in the code. Previously, when ensure_vertical_shell_thickness was set to Critical, we would default to a 0.2 factor even if the user had set sparse_infill_density to 0. According to the original logic in Slic3r, we should use a factor of 1 to prevent creating extra solid infill when printing a hollow model. This approach seems logical to me, so I've adjusted the logic here to give sparse_infill_density precedence over the ensure_vertical_shell_thickness setting.

Please let me know if this change was made intentionally on your part.

Comment (igiannakas) [reply src/libslic3r/PrintObject.cpp:3293]: Yes that was intentional as it was causing top layers to be unsupported…

Comment (igiannakas) [reply src/libslic3r/PrintObject.cpp:3293]: image

https://github.com/SoftFever/OrcaSlicer/pull/3235

towards the end of the thread

Comment (SoftFever) [reply src/libslic3r/PrintObject.cpp:3293]: @igiannakas Sorry I can't find the `sparse_infill_density` part.

**Comment by igiannakas** [comment]
OK my apologies @SoftFever - I missed the new code segment further up from the comment, where a factor is set. This is correct!

File: src/libslic3r/PrintObject.cpp (hunk 1 above)
Comment (SoftFever) [reply src/libslic3r/PrintObject.cpp:3293]: I'm referring a situation when user has these settings: sparse_infill_density = 0 and ensure_vertical_shell_thickness=Critical(previously further reduce solid infill option),
