### PR TITLE
Calibs: Process layer height

### LINKED ISSUE #11726: Calibration "red box" error with BBL A1 0.2mm nozzle default settings
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.1 f2d10a0

### Operating System (OS)

Windows

### OS Version

win 10

### Additional system information

Processor	Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz, 2808 Mhz, 6 Core(s), 6 Logical Processor(s)
Installed Physical Memory (RAM)	8.00 GB

### Printer

Bambu Lab A1

### How to reproduce

File - New Project
Printer Bambu Lab A1 0.2 nozzle (I used the SS profile, as there isn't one for a HS nozzle) - left at default values
Filament generic PLA
Process - 0.1.mm Standard @BBL A1 0.2 nozzle - left at default values

Select Calibration Test from top menu
Select any of the following tests:

Pressure Advance - Pattern
Retraction Test
Junction Deviation - Ringing Tower or Fast Tower
Input Shaping Frequency - Ringing Tower or Fast Tower
Input Shaping Damping - Ringing Tower or Fast Tower

OK to any of the option boxes, leave at default

### Actual results

The above tests all fail with a "red box" error mostly "Line width to small"
Pressure Advance - pattern fails with "Layer height cannot exceed nozzle diameter"

With a "red box" error, slicing is disabled and the test cannot be run without altering process parameters.

### Expected results

1. Be able to run the calibration tests with default printer and process settings.

2. Have a default profile for a BBL A1 hardened steel 0.2mm nozzle. 

### Project file & Debug log uploads

[Pressure Advance Test.zip](https://github.com/user-attachments/files/24321453/Pressure.Advance.Test.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

### Anything else?

Image

### PR DESCRIPTION
**Pull request by ianalexis**
Closes #11726

# Description

Removed hardcoded 0.2mm layer height.
Now it will stay in with the user process.

Also corrected several config assignments to use print_config instead of obj->config for consistency.

## Note

Didn't change PA PATTERN because i don't know if it may impact the calibration results for this specific test.

### CODE REVIEW

**Comment by igiannakas** [comment]
PA pattern should be performed at the user print preset settings. I think we should change it as well & confirm the custom gcode still produces the same output.. The PA calibration needs to target what the user will actually be printing at.

**Comment by SoftFever** [comment]
Hmm, the reason we use 0.2mm layer height here is because the model is designed in that way for each notch to be visible. 
E.g. if the layer height set to 0.3, the notch won't be visible

**Comment by SoftFever** [comment]
> PA pattern should be performed at the user print preset settings. I think we should change it as well & confirm the custom gcode still produces the same output.. The PA calibration needs to target what the user will actually be printing at.

I agree

**Comment by ianalexis** [comment]
> Hmm, the reason we use 0.2mm layer height here is because the model is designed in that way for each notch to be visible. E.g. if the layer height set to 0.3, the notch won't be visible

That's why my first approach was 0.2 unless it's under 0.5 nozzle size (the issue itself).

Edit: Can keep that logic for retraction test and the rest use the process height.
Or retraction test use the nearest 0.05 multiplier.

**Comment by SoftFever** [comment]
> > Hmm, the reason we use 0.2mm layer height here is because the model is designed in that way for each notch to be visible. E.g. if the layer height set to 0.3, the notch won't be visible
> 
> That's why my first approach was 0.2 unless it's under 0.5 nozzle size (the issue itself).

Maybe I missed something, but in this PR I can't find the logic you mentioned?

**Comment by ianalexis** [comment]
> Maybe I missed something, but in this PR I can't find the logic you mentioned?

I remove it in the last commit based in igianakas comment.

`float layer_height = std::min<float>(0.2f, printer_config->option<ConfigOptionFloats>("nozzle_diameter")->get_at(0) * 0.5f);`

**Comment by SoftFever** [comment]
> > Hmm, the reason we use 0.2mm layer height here is because the model is designed in that way for each notch to be visible. E.g. if the layer height set to 0.3, the notch won't be visible
> 
> That's why my first approach was 0.2 unless it's under 0.5 nozzle size (the issue itself).
> 
> Edit: Can keep that logic for retraction test and the rest use the process height. Or retraction test use the nearest 0.05 multiplier.

For the retraction test, to address the bug that you linked, we can handle those small nozzles whose maximum layer height is smaller than 0.2mm. We can reduce it to 0.1mm(or 0.2 nozzle) or 0.05mm(for 0.1 nozzle). 
For the max volume test, we should not use user settings as well. 

For others, I think it should respect the user settings if we are not already doing that.

File: src/slic3r/GUI/Plater.cpp [hunk 1]
```diff
@@ -12705,23 +12705,15 @@ void Plater::calib_retraction(const Calib_Params& params)
...
-    obj->config.set_key_value("wall_loops", new ConfigOptionInt(2));
-    obj->config.set_key_value("top_shell_layers", new ConfigOptionInt(0));
-    obj->config.set_key_value("bottom_shell_layers", new ConfigOptionInt(3));
-    obj->config.set_key_value("sparse_infill_density", new ConfigOptionPercent(0));
-    print_config->set_key_value("initial_layer_print_height", new ConfigOptionFloat(layer_height));
-    obj->config.set_key_value("layer_height", new ConfigOptionFloat(layer_height));
-    obj->config.set_key_value("alternate_extra_wall", new ConfigOptionBool(false));
-    obj->config.set_key_value("seam_position", new ConfigOptionEnum<SeamPosition>(spAligned));
-    obj->config.set_key_value("wall_sequence", new ConfigOptionEnum<WallSequence>(WallSequence::InnerOuter));
+    print_config->set_key_value("wall_loops", new ConfigOptionInt(2));
```
Comment (SoftFever) [inline src/slic3r/GUI/Plater.cpp]: Can we revert back to the object config? I try as much as possible to use the object setting whereever is allowed so that we reduce the chance of changing the print config to prevent the user from accidentally saving the settings.

Comment (ianalexis) [reply src/slic3r/GUI/Plater.cpp]: So that's the reason...
I found it confusing when wanting to change some value that the calibration preset override that's why i changed it here.
Ok reverting that, do you want me to change it in the other calibrations tests?
