### PR TITLE
Fix: Free camera panning/rotating fixed

### LINKED ISSUE #10266: Free camera navigation is broken
### OrcaSlicer Version

2.3.0

### Operating System (OS)

Linux

### OS Version

Manjaro, latest

### How to reproduce

1. New project.
2. Add some primitive.
3. Preferences > Use free camera ✅
4. Rotate the view in any way with the left mouse button.
5. Now pan the view with the middle mouse button - boom, it rotates to some random orientation.

### Expected results

Panning should not alter the rotation.

### Video

https://github.com/user-attachments/assets/e46ff9b1-d6cf-4501-b683-ae0610f33625

### PR DESCRIPTION
**Pull request by valerii-bokhan**
# Description

Fixes #10266

See the original code from the Prusa Slicer - https://github.com/prusa3d/PrusaSlicer/commit/4c16ce442ff312805390dad6a976267851b9f5da

```
#if ENABLE_AUTO_CONSTRAINED_CAMERA
    if (wxGetApp().app_config->get("use_free_camera") != "1")
        m_camera.recover_from_free_camera();
#endif // ENABLE_AUTO_CONSTRAINED_CAMERA
```

So, the `recover_from_free_camera` function should NOT be called when free camera is enabled. It's a typo and hard to say where it came from. Probably from BBS.

# Recordings

I am sorry, I am not good at using the free camera, but you can see that the original issue is gone - you can continue rotating from the previous position.

free_camera_bug

### CODE REVIEW

File: src/slic3r/GUI/GLCanvas3D.cpp [hunk 1]
```diff
@@ -4532,7 +4532,7 @@ void GLCanvas3D::on_mouse(wxMouseEvent& evt)
                 Vec3d orig = _mouse_to_3d(m_mouse.drag.start_position_2D, &z);
                 Camera& camera = wxGetApp().plater()->get_camera();
                 if (this->m_canvas_type != ECanvasType::CanvasAssembleView) {
-                    if (wxGetApp().app_config->get_bool("use_free_camera"))
+                    if (!wxGetApp().app_config->get_bool("use_free_camera"))
```
Comment (ianalexis) [inline src/slic3r/GUI/GLCanvas3D.cpp:4536]: Same code at 4469. Didint deeply check it yet but if you can take a look before i review this.

Comment (valerii-bokhan) [reply src/slic3r/GUI/GLCanvas3D.cpp:4536]: Yes, but the if-statement is correct there.

Comment (valerii-bokhan) [reply src/slic3r/GUI/GLCanvas3D.cpp:4536]: Btw, should I add the `//Orca:` comment here?

Comment (igiannakas) [reply src/slic3r/GUI/GLCanvas3D.cpp:4536]: yes please (Orca: comment).

Comment (valerii-bokhan) [reply src/slic3r/GUI/GLCanvas3D.cpp:4536]: Done

**Comment by igiannakas** [comment]
Looks good thank you!!
