### PR TITLE
Fix: generic filaments not showing on list

### LINKED ISSUE #12297: Filament selection does not work properly (2.3.2-beta)
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.2-beta

### Operating System (OS)

Linux

### OS Version

Arch

### Additional system information

_No response_

### Printer

-

### How to reproduce

 Select only one filament in Filament selection dialog (Generic PETG)

### Actual results

Filaments that weren't selected appear in the drop-down list. Sometimes there are just a few, sometimes quite a few, from different vendors. And those that were actually selected are missing (like Generic PETG in my case).

### Expected results

The drop-down menu should display the selected filaments.

### Project file & Debug log uploads

[orca.log](https://github.com/user-attachments/files/25318209/orca.log)

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Anything else?

Image

Image

### LINKED ISSUE #12922: Disappearing filaments
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.2

### Operating System (OS)

Windows

### OS Version

Windows 11

### Additional system information

_No response_

### Printer

Voron 2.4 / Voron v0 / Snapmaker u1

### How to reproduce

I delete the entire Orcaslicer folder under %appdata% to be sure to get a fresh start
Started Orca slicer and added my printers and couple generic filaments.
After that not all filaments that I added are showing.
If I go to Add filament again, the filament is not checked (for example Generic ASA, but it seems to happens randomly). I check the filament and complete the process but the filament does not appear in the list and when trying to add it again it is still not checked.
Somtimes it does add the filament, but then other filament that was installed just disappear from the list.

### Actual results

as commented above

### Expected results

filament to work as it did before

### Project file & Debug log uploads

[config.zip](https://github.com/user-attachments/files/26198749/config.zip)

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Sabriel-Koh**
# Description
This PR covers a few fixes related to the printer/filament selection dialog.

It should help some of the recent issues with Generic filaments, but I think it's possible that there may still be edge cases/sources of confusion that I have yet to find.

- Printer/filament selection 
  - Not sure if anyone else had this issue, but while working on this PR I kept having issues where the first time I opened the dialogs, none of my current selections would actually be selected. However, it would work as expected after that.(WebGuideDialog.cpp:1127)

     Refactored the code a little bit, calling SaveProfileData first to ensure that m_ProfileJson is updated, and placed them both in the same CallAfter call to make sure SaveProfileData is called first.

Bug:
image
image
Fixed:
image
image

- Printer's default filaments not being selected when going to the filament selection section of the initial setup
  - Seems like it was just a feature not in the WebGuideDialog class, unlike the previous setup wizard implementation.

Bug:
image
Fixed:
image

- Printer's default filament being selected, even if unavailable, making it seem like an extra filament was added (and also doesn't reappear on restart)
  - When the printer is loaded, an attempt to select its default filament is made, but the selection does not check for availability before it does so. Fixed by adding one.

Bug (only the CoPE was explicitly selected):
image
Fixed:
image

- Fix @\System filaments being added without the postfix
  - This tended to incorrectly add Bambu Lab specific filaments instead, since some are named like "Generic PLA" vs the "Generic PLA @\System" for the truly generic profile.
Fixes #12297 
Fixes #12922 

- Sometimes, when there is only 1 item in a sub-dropdown, the sub-dropdown does not show
  - In the dropdown code, there is a shortcut to return the hover_item index directly if the number of items shown is equal to the number of items in the combobox. However, for groups containing only 1 item, the grouping is incorrectly counted as an item itself, causing the subdropdown to not render. I will note that I saw cases where 1 item dropdowns rendered correctly, and think it was likely due to the presence of OTHER groups that contained more than 1 item (thus causing the dropdown to skip that shortcut).

Bug:
image
Fixed:
image

## Tests
Checking that the selected filaments remain selected in the dialog

#### Creality K1C tests
- Added Creality K1C on initial setup, cleared filament selection, and only selected Generic CoPE
- Added Generic ABS and Creality Generic ABS (one displays as "ABS" and the other as "Creality Generic ABS" in the subgroup
- Added a few other ABS filaments from non-generic vendors
- Removed all but Creality Generic ABS
- Removed Creality Generic ABS and added all Generic vendor filaments

### CODE REVIEW

**Comment by johnny-bit** [comment]
paging @yw4z

**Comment by yw4z** [comment]
i assume this one is better method for testing;
add generic filaments from system, creality and Qidi. try to mix similar types of filaments. or select all

i have tested and all generic ones listed. but im not sure this fixes other issue "filaments listing as incompatible" on  https://github.com/OrcaSlicer/OrcaSlicer/issues/12314 . i couldnt replicate that issue on my system. 

also its better to set title as "Fix: generic filaments not showing on list" (if only fixes generic ones)  "Fix: selected filaments not visible or listing as incompatible" (if also fixes incompatible issue) etc

**Comment by Sabriel-Koh** [comment]
Thanks for the feedback. I haven't looked into the "filaments listing as incompatible" yet since I had trouble replicating the issue as well. Updated the title and will try out some more tests 👍

File: src/slic3r/GUI/WebGuideDialog.cpp [hunk 1]
```diff
@@ -438,6 +439,50 @@ void GuideFrame::OnScriptMessage(wxWebViewEvent &evt)
                     wxString s2 = OneSelect["model"];
                     if (s1.compare(s2) == 0) {
                         m_ProfileJson["model"][m]["nozzle_selected"] = m_ProfileJson["model"][m]["nozzle_diameter"];
+
+                        // Automatically select default materials for this printer model
```
Comment (SoftFever) [inline src/slic3r/GUI/WebGuideDialog.cpp:443]: good one
