### PR TITLE
Fix custom profiles added/removed each other run

### LINKED ISSUE #8094: Custom Printers Missing on Every Other Launch
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.1.1+

### Operating System (OS)

Windows

### OS Version

Windows 11

### Additional system information

_No response_

### Printer

Custom Voron Profile

### How to reproduce

1. Launch Orca Slicer
2. Close Orca Slicer
3. Open Orca Slicer again

### Actual results

The first time the app is launched, my "User presets" printer list is missing from the drop down on the "Prepare" tab.  After closing Orca Slicer and reopening, the "User presets" list is back and so is my Voron preset.  This happens consistently every other app launch and has now for months.

### Expected results

The "User presets" list should always be present.

### Project file & Debug log uploads

There are no logs associated with this issue.

[Printer Preset.zip](https://github.com/user-attachments/files/18467363/Printer.Preset.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

This feels like something that is likely an issue on my end of things, but when I went from 2.1.1 to 2.2 and the issue remained I figured I would at least report it.  Seems unlikely that something like this would have gone unnoticed for so long if I wasn't the only person experiencing it.

### PR DESCRIPTION
**Pull request by Noisyfox**
Fix #8094

Replace #8102

Thanks @buzzhuzz for the initial investigation and PR

### CODE REVIEW

File: src/slic3r/Utils/PresetUpdater.cpp [hunk 1]
```diff
@@ -1079,9 +1079,9 @@ void PresetUpdater::priv::check_installed_vendor_profiles() const
     AppConfig *app_config = GUI::wxGetApp().app_config;
     const auto enabled_vendors = app_config->vendors();
 
-    std::vector<std::string> bundles;
+    std::set<std::string> bundles;
```
Comment (SoftFever) [inline src/slic3r/Utils/PresetUpdater.cpp:1082]: We need to make sure ORCA_FILAMENT_LIBRARY is loaded first, so that other profiles can inherit from it.
So we have to use vector here to make sure the insertion order is respected

File: src/slic3r/Utils/PresetUpdater.cpp [hunk 2]
```diff
@@ -1090,17 +1090,21 @@ void PresetUpdater::priv::check_installed_vendor_profiles() const
             std::string vendor_name = path.filename().string();
             // Remove the .json suffix.
             vendor_name.erase(vendor_name.size() - 5);
+            if (bundles.find(vendor_name) != bundles.end())continue;
+
+            const auto is_vendor_enabled = (vendor_name == PresetBundle::ORCA_DEFAULT_BUNDLE) // always update configs from resource to vendor for ORCA_DEFAULT_BUNDLE
```
Comment (SoftFever) [inline src/slic3r/Utils/PresetUpdater.cpp:1095]: 👍

**Review by SoftFever — CHANGES_REQUESTED** [review]

**Review by SoftFever — APPROVED** [review]
LGTM
