### PR TITLE
Proper support of Bambu LAN printers

### LINKED ISSUE #6169: Orcaslicer forgets access code for X1C in LAN mode constantly
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

macOS

### OS Version

Sonoma 14.5 (latest)

### Additional system information

Macbook Pro M1

### Printer

Bambu X1C (in LAN-only mode)

### How to reproduce

1. Open Orcaslicer
2. Go to device
3. Probably see that the printer in the unbound list
4. Click on it
5. Put in the passcode, see it move to the recent printers list
6. Close Orcaslicer, disconnect from the printer, or just let the laptop go to sleep so it disconnects
7. See that the printer as moved back to the unknown printers list, which will require a code again

### Actual results

Printer constantly goes to the unknown list requiring the access code when connecting.

### Expected results

Remember the access code. This worked fine before I updated to 2.1.1, continues to work fine in Bambu studio on the same machine with the same printer.

### Project file & Debug log uploads

No project file required. Can reproduce just while monitoring an existing print. Very frustrating during a multi-hour print that every time I wake the machine or go back into orca to check on the print, I have to dig out the access code again.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

_No response_

### LINKED ISSUE #8097: Bambulab printer not connected after startup in LAN mode
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.2

### Operating System (OS)

Linux

### OS Version

Debian trixie

### Additional system information

_No response_

### Printer

A1Mini/Bambulab

### How to reproduce

1. set LAN only Mode on printer
2. start orcaslicer
3. go device tab
4. -> Connecting...
5. tcp connected does not start with printer (can be seen in wireshark)
6. "Failed to connect to printer"
7.  click on the printer under My Device -> Printername (LAN)
8. I see tcp connection in wireshark is oppened an printer is listed as connected 

### Actual results

Printer does not get connected after startup. I see in wireshark that no connection is startet from orcaslicer. After clicking on "printernane (LAN)" the connection is started immediatly.

### Expected results

orcaslicer should connect on startup.

### Project file & Debug log uploads

[debug_Sun_Jan_19_10_44_12_18026.log](https://github.com/user-attachments/files/18468344/debug_Sun_Jan_19_10_44_12_18026.log)

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Anything else?

It is reproducible here and can be watched in wireshark.

### PR DESCRIPTION
**Pull request by Noisyfox**
**The latest download link can be found from the "Checks" tab above or [here](https://github.com/SoftFever/OrcaSlicer/pull/8256/checks). There should be an "artifact" dropdown on top of that page once the build is completed.**

This PR solves the following problems:

- Bind printers in different subnet
- Binded LAN printers are not automatically connected when switching to Device tab

32217e0ea2ed5434d8916ad5c46e69c4
2fc422ddd3a89ae675de426953e44c1b
image

Few improtant things to know:

The automatic printer info detection (ie, the step in the first image) doesn't work on MacOS, when you click "Connect" you will immediately be prompted to the second image to enter the printer details. (I don't know why but Bambu does not provide this capability on MacOS for their network plugin)

AFAIK, P1 series do not support automatic printer info detection (as tested by @SoftFever and myself), so the first step is gauranteed to fail, which is unfortunate but expected. Simply click the "Manual Setup" button (which will appear after clicking the "Connect" button then wait for a while) and enter the printer detail and you should be good to go.
If anything entered wrong, you could simply unbind the printer and do it all over again.

I know current binding flow is not very user-friendly, but consider how rare this will be used, I think it's OK. Given the current situation this is the best I could do with the closed-source Bambu network plugin.

I only have a P1 so I couldn't throughly test this PR. Please if you have different printers and home network configurations, your feedback are valuable to help validating and improving this PR, thanks in advance!

Fix #6169
Fix #8097

### CODE REVIEW

**Comment by TinyWorkshopDesign** [comment]
after trying around with tailscale and an x1c, seems that what is need to make it work is the use of a a fake packet on the port 2021.

i'm using this script:
https://gist.githubusercontent.com/Alex-Schaefer/72a9e2491a42da2ef99fb87601955cc3/raw/0bc2423a099ebde636b4067c4cb7316df2c9fa9c/bambu-ssdp-discovery.py

if I don't use this script at the moment of the connection the printer doesn't appear even with the use of the IP

**Comment by Noisyfox** [comment]
> after trying around with tailscale and an x1c, seems that what is needed to make it work is the use of a a fake packet on the port 2021.
> 
> i'm using this script: https://gist.githubusercontent.com/Alex-Schaefer/72a9e2491a42da2ef99fb87601955cc3/raw/0bc2423a099ebde636b4067c4cb7316df2c9fa9c/bambu-ssdp-discovery.py
> 
> if I don't use this script at the moment of the connection the printer doesn't appear even with the use of the IP

Have you tried the manual setup option?

**Comment by TinyWorkshopDesign** [comment]
yes, the printer doesn't appear unless I lunch the script

**Comment by Noisyfox** [comment]
> yes, the printer doesn't appear unless I lunch the script

Could you describe what steps have you done?

**Comment by TinyWorkshopDesign** [comment]
sure:
Open Orcaslicer (latest nightly)
Device->NoPrinter->Bind With access code insert-> ip+access code **Connect**  insert-> serial

the printer doesn't appear

to make it work:
Device->NoPrinter->Bind With access code insert-> ip+access code _launch the script_ **Connect**  insert-> serial

**Comment by Noisyfox** [comment]
> sure: Open Orcaslicer (latest nightly) Device->NoPrinter->Bind With access code insert-> ip+access code **Connect** insert-> serial
> 
> the printer doesn't appear
> 
> to make it work: Device->NoPrinter->Bind With access code insert-> ip+access code _launch the script_ **Connect** insert-> serial

What OS are you using?

**Comment by TinyWorkshopDesign** [comment]
> > sure: Open Orcaslicer (latest nightly) Device->NoPrinter->Bind With access code insert-> ip+access code **Connect** insert-> serial
> > the printer doesn't appear
> > to make it work: Device->NoPrinter->Bind With access code insert-> ip+access code _launch the script_ **Connect** insert-> serial
> 
> What OS are you using?

MacOS Sequoia 15.3 (24D60)

**Comment by Noisyfox** [comment]
> > > sure: Open Orcaslicer (latest nightly) Device->NoPrinter->Bind With access code insert-> ip+access code **Connect** insert-> serial
> > > the printer doesn't appear
> > > to make it work: Device->NoPrinter->Bind With access code insert-> ip+access code _launch the script_ **Connect** insert-> serial
> > 
> > 
> > What OS are you using?
> 
> MacOS Sequoia 15.3 (24D60)

I see, that might be a macos specific bug, I'll take a look soon.

**Comment by Noisyfox** [comment]
> > > sure: Open Orcaslicer (latest nightly) Device->NoPrinter->Bind With access code insert-> ip+access code **Connect** insert-> serial
> > > the printer doesn't appear
> > > to make it work: Device->NoPrinter->Bind With access code insert-> ip+access code _launch the script_ **Connect** insert-> serial
> > 
> > 
> > What OS are you using?
> 
> MacOS Sequoia 15.3 (24D60)

Btw, where did you download the nightly build from?

**Comment by TinyWorkshopDesign** [comment]
> > > > sure: Open Orcaslicer (latest nightly) Device->NoPrinter->Bind With access code insert-> ip+access code **Connect** insert-> serial
> > > > the printer doesn't appear
> > > > to make it work: Device->NoPrinter->Bind With access code insert-> ip+access code _launch the script_ **Connect** insert-> serial
> > > 
> > > 
> > > What OS are you using?
> > 
> > 
> > MacOS Sequoia 15.3 (24D60)
> 
> Btw, where did you download the nightly build from?

https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds

**Comment by Noisyfox** [comment]
> > > > > sure: Open Orcaslicer (latest nightly) Device->NoPrinter->Bind With access code insert-> ip+access code **Connect** insert-> serial
> > > > > the printer doesn't appear
> > > > > to make it work: Device->NoPrinter->Bind With access code insert-> ip+access code _launch the script_ **Connect** insert-> serial
> > > > 
> > > > 
> > > > What OS are you using?
> > > 
> > > 
> > > MacOS Sequoia 15.3 (24D60)
> > 
> > 
> > Btw, where did you download the nightly build from?
> 
> https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds

Try this one instead https://github.com/SoftFever/OrcaSlicer/pull/8256/checks

**Comment by TinyWorkshopDesign** [comment]
> > > > > > sure: Open Orcaslicer (latest nightly) Device->NoPrinter->Bind With access code insert-> ip+access code **Connect** insert-> serial
> > > > > > the printer doesn't appear
> > > > > > to make it work: Device->NoPrinter->Bind With access code insert-> ip+access code _launch the script_ **Connect** insert-> serial
> > > > > 
> > > > > 
> > > > > What OS are you using?
> > > > 
> > > > 
> > > > MacOS Sequoia 15.3 (24D60)
> > > 
> > > 
> > > Btw, where did you download the nightly build from?
> > 
> > 
> > https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds
> 
> Try this one instead https://github.com/SoftFever/OrcaSlicer/pull/8256/checks

doesn't work  after installing from the dmg and trying to launch it it gives me:

image

**Comment by Noisyfox** [comment]
> > > > > > > sure: Open Orcaslicer (latest nightly) Device->NoPrinter->Bind With access code insert-> ip+access code **Connect** insert-> serial
> > > > > > > the printer doesn't appear
> > > > > > > to make it work: Device->NoPrinter->Bind With access code insert-> ip+access code _launch the script_ **Connect** insert-> serial
> > > > > > 
> > > > > > 
> > > > > > What OS are you using?
> > > > > 
> > > > > 
> > > > > MacOS Sequoia 15.3 (24D60)
> > > > 
> > > > 
> > > > Btw, where did you download the nightly build from?
> > > 
> > > 
> > > https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds
> > 
> > 
> > Try this one instead https://github.com/SoftFever/OrcaSlicer/pull/8256/checks
> 
> doesn't work after installing from the dmg and trying to launch it it gives me:
> 
> image

https://github.com/SoftFever/OrcaSlicer?tab=readme-ov-file#how-to-install

**Comment by TinyWorkshopDesign** [comment]
> > > > > > > > sure: Open Orcaslicer (latest nightly) Device->NoPrinter->Bind With access code insert-> ip+access code **Connect** insert-> serial
> > > > > > > > the printer doesn't appear
> > > > > > > > to make it work: Device->NoPrinter->Bind With access code insert-> ip+access code _launch the script_ **Connect** insert-> serial
> > > > > > > 
> > > > > > > 
> > > > > > > What OS are you using?
> > > > > > 
> > > > > > 
> > > > > > MacOS Sequoia 15.3 (24D60)
> > > > > 
> > > > > 
> > > > > Btw, where did you download the nightly build from?
> > > > 
> > > > 
> > > > https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds
> > > 
> > > 
> > > Try this one instead https://github.com/SoftFever/OrcaSlicer/pull/8256/checks
> > 
> > 
> > doesn't work after installing from the dmg and trying to launch it it gives me:
> > image
> 
> https://github.com/SoftFever/OrcaSlicer?tab=readme-ov-file#how-to-install See point 3 under mac.

no, seem that the program is corrupterd ij some way, doesn't even appear in security
image

**Comment by Noisyfox** [comment]
> > > > > > > > > sure: Open Orcaslicer (latest nightly) Device->NoPrinter->Bind With access code insert-> ip+access code **Connect** insert-> serial
> > > > > > > > > the printer doesn't appear
> > > > > > > > > to make it work: Device->NoPrinter->Bind With access code insert-> ip+access code _launch the script_ **Connect** insert-> serial
> > > > > > > > 
> > > > > > > > 
> > > > > > > > What OS are you using?
> > > > > > > 
> > > > > > > 
> > > > > > > MacOS Sequoia 15.3 (24D60)
> > > > > > 
> > > > > > 
> > > > > > Btw, where did you download the nightly build from?
> > > > > 
> > > > > 
> > > > > https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds
> > > > 
> > > > 
> > > > Try this one instead https://github.com/SoftFever/OrcaSlicer/pull/8256/checks
> > > 
> > > 
> > > doesn't work after installing from the dmg and trying to launch it it gives me:
> > > image
> > 
> > 
> > https://github.com/SoftFever/OrcaSlicer?tab=readme-ov-file#how-to-install See point 3 under mac.
> 
> no, seem that the program is corrupterd ij some way, doesn't even appear in security image
> 
> ARM version btw

Then try the command line option.

**Comment by TinyWorkshopDesign** [comment]
> > > > > > > > > > sure: Open Orcaslicer (latest nightly) Device->NoPrinter->Bind With access code insert-> ip+access code **Connect** insert-> serial
> > > > > > > > > > the printer doesn't appear
> > > > > > > > > > to make it work: Device->NoPrinter->Bind With access code insert-> ip+access code _launch the script_ **Connect** insert-> serial
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > What OS are you using?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > MacOS Sequoia 15.3 (24D60)
> > > > > > > 
> > > > > > > 
> > > > > > > Btw, where did you download the nightly build from?
> > > > > > 
> > > > > > 
> > > > > > https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds
> > > > > 
> > > > > 
> > > > > Try this one instead https://github.com/SoftFever/OrcaSlicer/pull/8256/checks
> > > > 
> > > > 
> > > > doesn't work after installing from the dmg and trying to launch it it gives me:
> > > > image
> > > 
> > > 
> > > https://github.com/SoftFever/OrcaSlicer?tab=readme-ov-file#how-to-install See point 3 under mac.
> > 
> > 
> > no, seem that the program is corrupterd ij some way, doesn't even appear in security image
> > ARM version btw
> 
> Then try the command line option.

it will take some time, I need to DL xcode .... 😭

**Comment by Noisyfox** [comment]
> > > > > > > > > > > sure: Open Orcaslicer (latest nightly) Device->NoPrinter->Bind With access code insert-> ip+access code **Connect** insert-> serial
> > > > > > > > > > > the printer doesn't appear
> > > > > > > > > > > to make it work: Device->NoPrinter->Bind With access code insert-> ip+access code _launch the script_ **Connect** insert-> serial
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > What OS are you using?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > MacOS Sequoia 15.3 (24D60)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Btw, where did you download the nightly build from?
> > > > > > > 
> > > > > > > 
> > > > > > > https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds
> > > > > > 
> > > > > > 
> > > > > > Try this one instead https://github.com/SoftFever/OrcaSlicer/pull/8256/checks
> > > > > 
> > > > > 
> > > > > doesn't work after installing from the dmg and trying to launch it it gives me:
> > > > > image
> > > > 
> > > > 
> > > > https://github.com/SoftFever/OrcaSlicer?tab=readme-ov-file#how-to-install See point 3 under mac.
> > > 
> > > 
> > > no, seem that the program is corrupterd ij some way, doesn't even appear in security image
> > > ARM version btw
> > 
> > 
> > Then try the command line option.
> 
> it will take some time, I need to DL xcode .... 😭

Wait, what? I don't think so. It should be macos' built-in command.

**Comment by TinyWorkshopDesign** [comment]
> xattr -dr com.apple.quarantine <path_to_OrcaSlicer.app>

zsh: parse error near `\n'

**Comment by recursiveGecko** [comment]
Quick test on A1 using `OrcaSlicer_Linux_AppImage_PR-8256`, printer added & connected fine, the camera feed loads. Added printer persists across slicer restarts as expected.

image

image

**Comment by Noisyfox** [comment]
> > xattr -dr com.apple.quarantine <path_to_OrcaSlicer.app>
> 
> zsh: parse error near `\n'

Then try this
1. Hold command key and right click OrcaSlicer.app, from the context menu choose **Open**.
2. A warning window will pop up, click _Open_

**Comment by Noisyfox** [comment]
> Quick test on A1 using `OrcaSlicer_Linux_AppImage_PR-8256`, printer added & connected fine, the camera feed loads. Added printer persists across slicer restarts as expected.
> 
> image
> 
> image

And the printer is in a different subnet?

**Comment by recursiveGecko** [comment]
> Is the printer in a different subnet? Also did you have to go thought the manual setup process (enter printer name, serial number etc.) or not?

Yes, my PC is on `10.0.0.0/24` and my printer is on `10.0.1.0/24`.

When I first entered the IP & access code and clicked connect, it immediately reported "Failed to publish login request" (like it does in Bambu Studio), then I clicked "Manual setup", entered the other details, and it worked.

**Comment by Noisyfox** [comment]
> > Is the printer in a different subnet? Also did you have to go thought the manual setup process (enter printer name, serial number etc.) or not?
> 
> Yes, my PC is on `10.0.0.0/24` and my printer is on `10.0.1.0/24`.
> 
> When I first entered the IP & access code and clicked connect, it immediately reported "Failed to publish login request" (like it does in Bambu Studio), then I clicked "Manual setup", entered the other details, and it worked.

Cool thanks for the test! So the automatic setup doesn't work properly so far... But good to know at least manual setup works.

**Comment by Cartrigger** [comment]
Here with a A1, it automatically connected while switching to devices :D
All features are working as expected too.

(Windows)

**Comment by recursiveGecko** [comment]
> I don't even get the same "Failed to publish login request" error with P1... God knows what Bambu did with their network plugin & firmware...

Does the P1 firmware listen on different ports, or does the network plugin try to connect to a different port when it's connecting to a P1?

On my A1, I previously observed the following:

> When connecting to the printer through auto-discovery, Bambu Studio successfully connects to the printer on port 8883
> When connecting to the printer by IP, Bambu Studio attempts to connect to the printer on port 3000 and receives a TCP reset, indicating that it's not connecting to the right port.

**Comment by Noisyfox** [comment]
> Does the P1 firmware listen on different ports, or does the network plugin try to connect to a different port when it's connecting to a P1?

It could be the case, though we can't really fix that since it fully closed source.

File: src/slic3r/GUI/ReleaseNote.cpp [hunk 1]
```diff
@@ -1922,6 +1922,7 @@ void InputIpAddressDialog::on_ok(wxMouseEvent& evt)
     m_trouble_shoot->Hide();
     std::string str_ip = m_input_ip->GetTextCtrl()->GetValue().ToStdString();
     std::string str_access_code = m_input_access_code->GetTextCtrl()->GetValue().ToStdString();
+    std::string str_name = m_input_printer_name->GetTextCtrl()->GetValue().Strip(wxString::both).ToStdString();
     std::string str_sn = m_input_sn->GetTextCtrl()->GetValue().ToStdString();
     std::string str_model_id = "";
```
Comment (eolder) [inline src/slic3r/GUI/ReleaseNote.cpp:1928]: RE: 
> > Thanks, just tested and this build worked for me!
> > edit: if you type the serial wrong (or in lowercase) it will crash.
> > ```
> > Exceptions:
> > Exception Code :c0000005 ACCESS_VIOLATION
> > Exception Flag :0x0 NumberParameters :2 
> > Param 0 :0x0 
> > Param 1 :0x10 
> > Context :00000085FC4FF0C0 
> > ContextFlag : 0x10005f, EFlags: 0x10206 
> > Fault address:  0xCA3397E1 0x1:0x1687E1 C:\Users\User\AppData\Roaming\OrcaSlicer\plugins\bambu_networking.dll
> > ```
> 
> I don't think I could do much about it unfortunately.

Do we know if BBL serials can contain lower case characters? I found several online that are all a mix of numbers and uppercase characters.

Assuming they can't then this patch would prevent some confusing crashes.
```
--- a/src/slic3r/GUI/ReleaseNote.cpp
+++ b/src/slic3r/GUI/ReleaseNote.cpp
@@ -1926,6 +1926,8 @@ void InputIpAddressDialog::on_ok(wxMouseEvent& evt)
     std::string str_sn = m_input_sn->GetTextCtrl()->GetValue().ToStdString();
     std::string str_model_id = "";
 
+    std::transform(str_sn.begin(), str_sn.end(), str_sn.begin(), std::toupper);
+
     auto it = m_models_map.right.find(m_input_modelID->GetStringSelection().ToStdString());
     if (it != m_models_map.right.end()) {
         str_model_id = it->get_left();
```

Comment (Noisyfox) [reply src/slic3r/GUI/ReleaseNote.cpp:1928]: That might work.

Comment (Noisyfox) [reply src/slic3r/GUI/ReleaseNote.cpp:1930]: Done

**Comment by Splarkszter** [comment]
Awesome! Thank you so much! This fixes it!!!

**Comment by joshajohnson** [comment]
Thanks for this PR, it fixes the forgetting of the pairing PIN on my Win 10 machine after sleep.

File: src/slic3r/GUI/ReleaseNote.cpp (hunk 1 above)
Comment (eolder) [reply src/slic3r/GUI/ReleaseNote.cpp:1930]: Sweet, thanks!

**Comment by pleasantone** [comment]
Given that flat packs are now building again, can we get this merged? @Noisyfox ?

**Comment by Wraith324** [comment]
Please, please merge this.  This fix actually works.  For the first time I can bind to Orca Slicer without discovery.  How about it @Noisyfox?

**Comment by TinyWorkshopDesign** [comment]
after some thinkering I managed it to work (was some weird permissions issue in my installation)

can confirm that the fix works with tailscale too

**Comment by ffafe5** [comment]
> > > > > > sure: Open Orcaslicer (latest nightly) Device->NoPrinter->Bind With access code insert-> ip+access code **Connect** insert-> serial
> > > > > > the printer doesn't appear
> > > > > > to make it work: Device->NoPrinter->Bind With access code insert-> ip+access code _launch the script_ **Connect** insert-> serial
> > > > > 
> > > > > 
> > > > > What OS are you using?
> > > > 
> > > > 
> > > > MacOS Sequoia 15.3 (24D60)
> > > 
> > > 
> > > Btw, where did you download the nightly build from?
> > 
> > 
> > https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds
> 
> Try this one instead https://github.com/SoftFever/OrcaSlicer/pull/8256/checks

I downloaded the latest nightly today, and through it was able to see the new options for adding a printer by access code and IP and serial number. Neither of those worked for me, yet Home Assistant has been able to connect via the serial# and IP without issue. I tried this one you linked and didn't make it very far because the setup wizard is broken and does not add the printer type.
