### PR TITLE
IF-enable PA in IS and Cornering Calibs

### LINKED ISSUE #11061: Input Shaping calibrations set Pressure Advance value at 0
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.1

### Operating System (OS)

Windows

### OS Version

10

### Additional system information

_No response_

### Printer

Neptune 3 Plus with Klipper

### How to reproduce

1. Check material settings (Pressure Advance value = 0.06) 

Image
2. Create IS calibration tower
3. Check material settings again

### Actual results

Pressure Advance value = 0

Image

### Expected results

Pressure Advance value = 0.06

### Project file & Debug log uploads

[Input shaping Frequency test.zip](https://github.com/user-attachments/files/22948085/Input.shaping.Frequency.test.zip)

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Anything else?

Disabled (or 0 value) pressure advance causes tearing and makes results almost impossible to read.
Here's comparison:

Image

### PR DESCRIPTION
**Pull request by ianalexis**
# Description

Closes #11061

If a PA was enables keep it that way, but if it wasn't it will be override to 0 to avoid previous issue (#10481).

Thanks @lemonhole

### CODE REVIEW

File: src/slic3r/GUI/Plater.cpp [hunk 1]
```diff
@@ -12474,13 +12475,16 @@ void Plater::calib_input_shaping_freq(const Calib_Params& params)
         printer_config->set_key_value("machine_max_jerk_y", new ConfigOptionFloats{std::max(printer_config->option<ConfigOptionFloats>("machine_max_jerk_y")->values.front(), jerk_value)});
         print_config->set_key_value("default_jerk", new ConfigOptionFloat(0));
     }
+
+    if (!filament_config->option<ConfigOptionBools>("enable_pressure_advance")->get_at(0)) {
+        filament_config->set_key_value("enable_pressure_advance", new ConfigOptionBools {true});
+        filament_config->set_key_value("pressure_advance", new ConfigOptionFloats { 0.0 });
```
Comment (Noisyfox) [inline src/slic3r/GUI/Plater.cpp:12481]: What about `adaptive_pressure_advance`?

Comment (ianalexis) [reply src/slic3r/GUI/Plater.cpp:12481]: This is just an override if there is no PA set to avoid the usage of a high value in the firmware.
If PA is enabled it stay as it is. And if APA is enabled, PA must be enabled too.
Maybe I could disable APA just in case somebody set APA and later disables PA. Are you referring to that?

File: src/slic3r/GUI/Plater.cpp [hunk 2]
```diff
@@ -12474,13 +12475,16 @@ void Plater::calib_input_shaping_freq(const Calib_Params& params)
...
+    }
+
     printer_config->set_key_value("resonance_avoidance", new ConfigOptionBool{false});
     filament_config->set_key_value("slow_down_layer_time", new ConfigOptionFloats { 0.0 });
     filament_config->set_key_value("slow_down_min_speed", new ConfigOptionFloats { 0.0 });
     filament_config->set_key_value("slow_down_for_layer_cooling", new ConfigOptionBools{false});
-    filament_config->set_key_value("enable_pressure_advance", new ConfigOptionBools {true});
-    filament_config->set_key_value("pressure_advance", new ConfigOptionFloats { 0.0 });
-    filament_config->set_key_value("adaptive_pressure_advance", new ConfigOptionBools{false});
```
Comment (Noisyfox) [inline src/slic3r/GUI/Plater.cpp:12483]: Since the original code disabled apa explicitly, but the new code says nothing about it, I'm just wondering if you forgot something or that was intentional.

Comment (ianalexis) [reply src/slic3r/GUI/Plater.cpp:12483]: Yeah, maybe I should force disable it if PA isn't enabled. Just to be safe and doesn't harm.

Comment (ianalexis) [reply src/slic3r/GUI/Plater.cpp:12483]: I can do it in about 9hrs, so if you want to merge it now and you can add that line I won't get mad hahaha.

Comment (ianalexis) [reply src/slic3r/GUI/Plater.cpp:12483]: Done
