### PR TITLE
Material Type standarization + Technical Filament Types

### LINKED ISSUE #10181: Recomended  nozzel tempeture limit to low
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.0

### Operating System (OS)

Windows

### OS Version

win 10 pro

### Additional system information

_No response_

### Printer

valkyrie  HT pro

### How to reproduce

if you set the recomened  nozzle  tempreture to the manufactures  specification  in this setting you get an error message 

### Actual results

Image

### Expected results

not to put a cap on the nozzle temperature as low as 300C

### Project file & Debug log uploads

[temperror0.zip](https://github.com/user-attachments/files/21332197/temperror0.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ianalexis**
# Description

- Added filament types used in filament profiles + ones that exist in the market.
- Each filament type have it's own:
  - Min/Max temp. fixes #10181 
  - Min/Max Chamber temp.
  - Adhesion coefficient
  - Brim
    - Yield Strength
    - Thermal Length 
- Modified the FilamentTempType logic to use the Max temp.
  - LowTemp = Max temp <= 250 
  - HighLowCompatible = Max temp <= 280
  - HighTemp = Max temp > 280

> [!NOTE]
> Some "filament types" i found in some profiles that are "wrong" or not a material technical name so i didin't add them:
> - ABS Material4Print Natur
> - Breakaway Support
> - PACF Pro
> - PETG Polymax
> - S-Multi
> - S-PAHT
> - Silk
> - TPU-AMS

---

# Posible evolution
add "modifiers" options to reduce the material list:

- Base Material (Base material: PLA, ABS, ASA, PA, PC, PEI, etc.)
 - Type:
   - PLA: Aero
   - PA: 6, 11, 12
   - PEI: 1010, 9085
   - PET: G ?
   - PC: ABS, PBT
 - Reinforcer:
   - CF
   - GF
   
Result material should be [BASE MATERIAL]-[TYPE]-[Reinforcer]
But i'm not going to code this unless there is interest from @SoftFever so you choose.

### CODE REVIEW

File: src/slic3r/GUI/ConfigManipulation.cpp [hunk 1]
```diff
@@ -59,10 +59,24 @@ void ConfigManipulation::check_nozzle_recommended_temperature_range(DynamicPrint
...
+    if (!get_filament_temp_range(filament_type, min_recommended_temp, max_recommended_temp)){
+        filament_type = "Unknown";
+    }
+
     wxString msg_text;
     bool     need_check = false;
-    if (temperature_range_low < 190 || temperature_range_high > 300) {
-        msg_text += _L("The recommended minimum temperature is less than 190°C or the recommended maximum temperature is greater than 300°C.\n");
+    if (temperature_range_low < min_recommended_temp || temperature_range_high > max_recommended_temp) {
+        msg_text += wxString::Format(_L("%s recommended temperature range is [%d, %d]°C."),
```
Comment (afmenez) [inline src/slic3r/GUI/ConfigManipulation.cpp]: Please use "\u2103" instead of "°C".

Comment (ianalexis) [reply src/slic3r/GUI/ConfigManipulation.cpp]: Done, obrigado cara.
But before we resolve this conversation.
What validations of this type should be taken into account?
Perhaps we could generate an action for this type of validation. I'm asking you because you're the expert in this area.

File: src/libslic3r/PrintConfig.cpp [hunk 2]
```diff
@@ -53,6 +53,87 @@ namespace Slic3r {
...
+        {"PETG", 190, 300},
+        {"PETG-CF", 210, 290},
+        {"PETG-CF10", 220, 260},
+        {"PETG-GF", 230, 250},
+        {"PHA", 190, 240},
+        {"PI", 390, 410},
+        {"PLA", 160, 300},
+        {"PLA-AERO", 230, 270},
+        {"PLA-CF", 190, 250},
+        {"POM", 210, 220},
```
Comment (RF47) [inline src/libslic3r/PrintConfig.cpp]: el pom de grilon se imprime a 240

File: src/libslic3r/PrintConfig.cpp [hunk 3]
```diff
@@ -53,6 +53,87 @@ namespace Slic3r {
...
+        {"PAHT-GF", 270, 310},
+        {"PC", 240, 300},
+        {"PC-ABS", 230, 270},
+        {"PC-CF", 270, 295},
+        {"PCL", 130, 170},
+        {"PCTG", 220, 300},
+        {"PE", 175, 260},
+        {"PE-CF", 175, 260},
+        {"PE-GF", 230, 270},
+        {"PEI", 350, 390},
```
Comment (RF47) [inline src/libslic3r/PrintConfig.cpp]: creo que hay 2 tipos de pei, el ultem 1010 y el 9085 y se imprimen a diferente temp.

File: src/libslic3r/PrintConfig.cpp [hunk 4]
```diff
@@ -53,6 +53,87 @@ namespace Slic3r {
...
+        {"PA11-GF", 275, 295},
+        {"PA12", 250, 270},
+        {"PA12-CF", 250, 300},
+        {"PA12-GF", 255, 270},
+        {"PAHT", 260, 310},
+        {"PAHT-CF", 270, 310},
+        {"PAHT-GF", 270, 310},
+        {"PC", 240, 300},
+        {"PC-ABS", 230, 270},
+        {"PC-CF", 270, 295},
```
Comment (RF47) [inline src/libslic3r/PrintConfig.cpp]:
``` cpp
 {"PC-PBT", 260, 300},```

File: src/libslic3r/PrintConfig.cpp (hunk 3 above)
Comment (ianalexis) [reply src/libslic3r/PrintConfig.cpp]: Si, pero el rango de temperaturas es basicamente identico.

Comment (ianalexis) [reply src/libslic3r/PrintConfig.cpp]: tenes razon, lo voy a cambiar

File: src/slic3r/GUI/ConfigManipulation.cpp (hunk 1 above)
Comment (afmenez) [reply src/slic3r/GUI/ConfigManipulation.cpp]: Sorry, I am not an expert, just trying to make the GUI more uniform. :)

Comment (afmenez) [reply src/slic3r/GUI/ConfigManipulation.cpp]: I believe these need to be an `u8""` string...

Comment (ianalexis) [reply src/slic3r/GUI/ConfigManipulation.cpp]: > Sorry, I am not an expert, just trying to make the GUI more uniform. :)

You are always taking care about this, thats why. I will take a look in the future if there is something that we could automate. It was already with °C so somebody already miss that.

**Comment by LupusTheCanine** [comment]
How would you deal with something like ColorFabb PLA-LW-HT?

**Comment by ianalexis** [comment]
> How would you deal with something like ColorFabb PLA-LW-HT?


Pla lw ht is something like pla foam AFAIK (correct me if I'm wrong, I didn't know about it until now).
If is something different we should see what it is and maybe creating a new category there and see what values they should use. 

Now days what type is used for it?
Pla?
If so, it uses the pla's brim and adhesion coefficients.
A custom one outside the list?
If so, it uses the generic default values.

No matter what, probably they are not the correct ones and whit this modification it will be really easy to add them.
And something like that happens with extreamly different materials like Peek.

**Comment by LupusTheCanine** [comment]
@ianalexis it is PLA that has foaming agent added in and was further modified to resist higher temperatures. So, two modifiers which is my concern with the proposed scheme.

**Comment by ianalexis** [comment]
> @ianalexis it is PLA that has foaming agent added in and was further modified to resist higher temperatures. So, two modifiers which is my concern with the proposed scheme.

PLA-HT changes usually impact the final piece rather than the printing parameters, so I did not consider creating an extra subtype.

From what I saw in many ColorFabb posts, both (PLA-LW and PLA-LW-HT) fall perfectly within the PLA-FOAM range. The differences between the two lie in the definition of each profile (such as first layer temperature, bed temperature, and flow coefficients), but the base type should be PLA-FOAM.

File: src/libslic3r/MaterialType.cpp [hunk 5]
```diff
@@ -0,0 +1,169 @@
...
+        {"PEEK",        350, 460, 80, 100, 1,   0.02, 200},
+        {"PEEK-CF",     380, 410, 80, 100, 1,   0.02, 200},
+        {"PEEK-GF",     375, 410, 80, 100, 1,   0.02, 200},
+        {"PEKK",        325, 400, 80, 100, 1,   0.02, 200},
+        {"PEKK-CF",     360, 400, 80, 100, 1,   0.02, 200},
+        {"PES",         340, 390, 80, 100, 1,   0.02, 200},
+        {"PET",         200, 290, 0,  55,  2,   0.3 , 100},
+        {"PET-CF",      240, 320, 0,  55,  2,   0.3 , 100},
+        {"PET-GF",      280, 320, 0,  55,  2,   0.3 , 100},
+        {"PETG",        190, 260, 0,  55,  1,   0.3 , 100},
```
Comment (SoftFever) [inline src/libslic3r/MaterialType.cpp]: The adhesion_coefficient for PETG should be `2`

File: src/libslic3r/MaterialType.cpp [hunk 6]
```diff
@@ -0,0 +1,169 @@
...
+        {"PA12-GF",     255, 270, 50, 60,  1,   0.02, 100},
+        {"PAHT",        260, 310, 55, 65,  1,   0.02, 200},
+        {"PAHT-CF",     270, 310, 55, 65,  1,   0.02, 200},
+        {"PAHT-GF",     270, 310, 55, 65,  1,   0.02, 200},
+        {"PC",          240, 300, 60, 70,  1,   0.02, 40},
+        {"PC-ABS",      230, 270, 60, 70,  1,   0.02, 80},
+        {"PC-CF",       270, 295, 60, 70,  1,   0.02, 80},
+        {"PC-PBT",      260, 300, 60, 70,  1,   0.02, 40},
+        {"PCL",         130, 170, 0,  45,  1,   0.02, 200},
+        {"PCTG",        220, 300, 0,  55,  1,   0.02, 200},
```
Comment (SoftFever) [inline src/libslic3r/MaterialType.cpp]: The adhesion_coefficient for PCTG should be `2`

Comment (ianalexis) [reply src/libslic3r/MaterialType.cpp]: Done, my mistake when loading values.
If you like and merge this PR i was thinking to update the values in another PR.
The most of them now are the "default" ones and there are some that i know we should change them.

**Review by SoftFever — APPROVED** [review]

**Comment by SoftFever** [comment]
LGTM
Thank you
