### PR TITLE
Fix filament editor crash on Linux

### LINKED ISSUE #8895: Crash when edit filament
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.0-rc

### Operating System (OS)

Linux

### OS Version

Ubuntu 24.04.2 LTS

### Additional system information

_No response_

### Printer

Voron Trident 350

### How to reproduce

1. Click to edit filament
2. Crash

### Actual results

The app is crashed and closed

### Expected results

It must open filament profile edit screen

### Project file & Debug log uploads

any project, independet

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Noisyfox**
Fix #8895

In some cases, updating multiline text fields during dialog pop up crashes GTK. This PR changes the order by updating the fields first then show the UI.

### CODE REVIEW

File: src/slic3r/GUI/PresetComboBoxes.cpp [hunk 1]
```diff
@@ -796,15 +796,6 @@ bool PlaterPresetComboBox::switch_to_tab()
...
         return false;
 
-    //BBS  Select NoteBook Tab params
-    if (tab->GetParent() == wxGetApp().params_panel())
-        wxGetApp().mainframe->select_tab(MainFrame::tp3DEditor);
-    else {
-        wxGetApp().params_dialog()->Popup();
-        tab->OnActivate();
-    }
-    tab->restore_last_select_item();
```
Comment (SoftFever) [inline src/slic3r/GUI/PresetComboBoxes.cpp:806]: Any idea it will change any behavior if we remove this function?

**Review by SoftFever — APPROVED** [review]
LGTM
