### PR TITLE
3d honeycomb bug fix (with infill combination) improve bridge direction

### LINKED ISSUE #12002: Automatic internal bridge infill direction may cause full bridges with cross hatch sparse infill, and fail the top layers of the print
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.1

### Operating System (OS)

Linux

### OS Version

bazzite-dx 43.20260101

### Additional system information

_No response_

### Printer

Creality K1 Max

### How to reproduce

1. Have a model, e.g. [cube.zip](https://github.com/user-attachments/files/24699259/cube.zip)
   - This model is a simple cube with 30x30x29 mm, and rotated 45 degrees
   - I used a different model myself, but this simple cube is a good reproduction without having to share my model
2. Set the sparse infill pattern to cross hatch and direction to 45
3. Set the internal bridge infill direction to 0 (auto)
4. Set top shell layers to 3, and bottom shell layers to 3
5. Slice
6. Check the sparse infill and the layers above

### Actual results

The last sparse infill layer has a direction of 0 degrees in the following screenshot.
Additionally, this direction has been the same for at least a couple layers.
Image

Going one layer up, showing the internal bridge infill, this layer follows the same direction of its lower siblings of 0 degrees.
Image

This results in a full bridge that spans from one edge to the other edge of the model, which is not printed correctly, especially on bigger models. Additionally, depending on the number of layers (as is the case with a 30x30x29 mm cube), the first internal solid infill layer also follows the same direction. In my case, the bridge layer sagged, and the solid infill on top of that did not end up smooth, and the layers above caused the nozzle to heavily grind into the model.

### Expected results

The internal bridge layer direction should not follow the last sparse infill layer direction, and instead cross it (ideally with 90 degrees).

### Project file & Debug log uploads

[cube.zip](https://github.com/user-attachments/files/24699259/cube.zip)

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Anything else?

I realize that I could have changed the internal bridge infill direction to anything else than 0, however:
- I was not aware that keeping it 0 (auto) would cause any problems until I printed my model (I was not even aware of this setting), and auto suggests that it chooses the best direction itself.
- In the model that I printed, I have more internal bridges that would've been affected by setting the direction manually and may have caused a conflict because they all follow the same direction, instead of an automatic calculation per bridge

It seems that this is caused by the unique combination of rotating a model 45 degrees, using cross hatch infill, and having just enough layers that it slices the layers with this direction.

### PR DESCRIPTION
**Pull request by RF47**
# Description

PR inspired by #12046
This PR fixes a bug in 3D honeycomb where using infill combination causes the infill to shift, resulting in incorrect bridge detection. This also fix artifacts with variable layer height.
# Screenshots/Recordings/Graphs
# Before:
Bug 1: unsupported bridges
image
Bug 2: rotated pattern with infill combination
image

# After:
image
image
3D honeycomb and crosshatch infill patterns, bridge direction on top layer.
image
Fix #12002

### CODE REVIEW

**Comment by discip** [comment]
@RF47
What about accounting for object rotation, as was done in #12046?

**Comment by RF47** [comment]
> @RF47 What about accounting for object rotation, as was done in #12046?

image
I think it works well, but I need to run some tests to see if I'm missing anything. Ultimately, I'll just leave the 3dHoneycomb fix.

File: src/libslic3r/Fill/Fill3DHoneycomb.cpp [hunk 1]
```diff
@@ -224,7 +224,7 @@ void Fill3DHoneycomb::_fill_surface_single(
     // This means that the resultant infill won't be an ideal truncated octahedron,
     // but it should look better than the equivalent quantised version
 
-    coordf_t layerHeight = scale_(thickness_layers);
+    coordf_t layerHeight = scale_(params.layer_height);
```
Comment (tome9111991) [inline src/libslic3r/Fill/Fill3DHoneycomb.cpp]: maybe `coordf_t layerHeight = scale_(1.0);` is better? 
because:
The code expects an integer-based step (1, 2, 3 layers). scale_(1.0) provides the mathematical
      "1" the formula needs. If you use layer_height (e.g., 0.2mm), the value is 5x smaller, which stretches the pattern
      vertically by 5x, making it look distorted and inconsistent with the standard version.
`scale_(1.0)` fixes the bug by keeping the lines stacked perfectly on top of each other, while maintaining
  the pattern's original look.

i have tried, looks not bad with scale_(1.0)

Comment (RF47) [reply src/libslic3r/Fill/Fill3DHoneycomb.cpp]: You're right. Done.

**Comment by ianalexis** [comment]
So, i think that we can comment out that part of the code or force it to 1 because this is trying to deform the pattern.

Current Combined/not combined
imagen

This PR Combined/not combined
imagen

@gringer you commented in that part of the code that you adjust it because "it should look better" but i think that this looks better. What do you think about this?

**Comment by gringer** [comment]
@ianalexis thanks for calling me in on this.

TLDR: I'd rather you didn't for a couple of different reasons, but if you think it looks better, then go ahead.

This is a low-density infill pattern. This adjustment was so that people using this infill at high densities would see a truncated octahedron-like pattern (in terms of how the individual alternate layering works) - and in terms of this infill, 25% is high. If people want to use high-density infill when they're printing, why not use a cubic or rectilinear infill?

The adjustment also [makes calculating density more predictable](https://github.com/prusa3d/PrusaSlicer/pull/6434#issuecomment-826469643), which is important for making the infill percentage / density relationship consistent across different infill patterns and layer heights. This was a complaint [from a youtuber](https://www.youtube.com/watch?v=upELI0HmzHc&t=212s) that tested out an earlier version of my infill pattern.

It is possible that the "high-density infill pattern" is too detailed, and there should be another preset pattern between 25% and 42% (where it switches again to a different pattern), but that seemed like too much effort for me to put into something that would have only minor effects on the resulting infill appearance (because of how dense it is).

**Comment by ianalexis** [comment]
> TLDR: I'd rather you didn't for a couple of different reasons, but if you think it looks better, then go ahead.

Thanks you for your quick response!

The main issue here is not that "it looks better" sideways but the bridging calculation.
Due it doing some flipping when using infill combination things like this happen:

- 15%
  - Current:
    imagen
  - with this change it's done correctly:
    imagen
- 9%
  - Current:
     imagen
  - This pr:
    imagen

- Currently there are some "magic numbers" where they match like this 10%
  - current
    imagen
  - this pr 
    imagen

I couldnt find the logic behind the "magic numbers" yet but maybe there is a way to fix the wrong bridge calculation that im not seeing.

**Comment by ianalexis** [comment]
Another issue with the current implementation while using infill combination is adaptive layers.

Same cube, just combined/not combined

Current
imagen


this pr
imagen

**Comment by tome9111991** [comment]
> I couldnt find the logic behind the "magic numbers" yet but maybe there is a way to fix the wrong bridge calculation that im not seeing.

Without this PR, it looks like the bridge is still being printed where infill is expected, but with the bug, the infill is generated incorrectly.

My theory is that the scaling is wrong.

**Comment by gringer** [comment]
Okay, in that case go ahead. The scaling should be [only] enforcing an integer count for the number of vertical layers per pattern, but if it's not doing that properly, or if it looks better without it (including bridging issues), it doesn't make sense to keep it in.

**Comment by ianalexis** [comment]
@RF47 Comment that part out just in case but lets keep 1.
